import { defineConfig } from 'vitepress'

export default defineConfig({
  transformHtml(code, _id, ctx) {
    if (!ctx.page.startsWith('felix/') && ctx.page !== 'felix.md') return
    return code.replace('<html ', '<html class="felix" ')
  },
  title: 'Templates',
  description: 'Design-language guides by Axel Diaz',
  appearance: 'force-dark',
  cleanUrls: true,
  head: [
    ['link', { rel: 'preconnect', href: 'https://fonts.googleapis.com' }],
    ['link', { rel: 'preconnect', href: 'https://fonts.gstatic.com', crossorigin: '' }],
    ['link', { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css2?family=Space+Grotesk:wght@500;600;700&family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&family=JetBrains+Mono:wght@400;600&display=swap' }]
  ],
  themeConfig: {
    nav: [
      { text: 'Home', link: '/' }
    ],
    sidebar: {
      '/folio': [{ text: 'Folio foundations', items: [{ text: 'Overview', link: '/folio' }, { text: 'Principles and tokens', link: '/folio/foundations' }, { text: 'CSS implementation', link: '/folio/tokens' }] }, { text: 'Folio components', items: [{ text: 'Full live catalog', link: '/folio/components' }, { text: 'Charts', link: '/folio/charts' },  { text: 'Layouts', link: '/folio/layouts' }, { text: 'Dashboard', link: '/folio/overview' }] }],
      '/spark': [{ text: 'Spark foundations', items: [{ text: 'Overview', link: '/spark' }, { text: 'Principles and tokens', link: '/spark/foundations' }, { text: 'CSS implementation', link: '/spark/tokens' }] }, { text: 'Spark components', items: [{ text: 'Full live catalog', link: '/spark/components' }, { text: 'Charts', link: '/spark/charts' },  { text: 'Layouts', link: '/spark/layouts' }, { text: 'Dashboard', link: '/spark/overview' }] }],

      '/felix': [
        {
          text: 'Foundations',
          items: [
            { text: 'Overview', link: '/felix' },
            { text: 'Principles', link: '/felix/principles' },
            { text: 'Colors', link: '/felix/colors' },
            { text: 'Typography', link: '/felix/typography' },
            { text: 'Illustrations', link: '/felix/illustrations' }
          ]
        },
        {
          text: 'Components',
          items: [
            { text: 'Overview', link: '/felix/components/' },
            { text: 'Full UI catalog', link: '/felix/components/catalog' },
            { text: 'Atoms', collapsed: true, link: '/felix/components/atoms', items: [
              { text: 'Amount', link: '/felix/components/atoms#amount' },
              { text: 'Avatar', link: '/felix/components/atoms#avatar' },
              { text: 'Badge', link: '/felix/components/atoms#badge' },
              { text: 'Bubble', link: '/felix/components/atoms#bubble' },
              { text: 'Button', link: '/felix/components/atoms#button' },
              { text: 'Checkbox', link: '/felix/components/atoms#checkbox' },
              { text: 'CoinLoader', link: '/felix/components/atoms#coinloader' },
              { text: 'Dots', link: '/felix/components/atoms#dots' },
              { text: 'IconButton', link: '/felix/components/atoms#iconbutton' },
              { text: 'Input', link: '/felix/components/atoms#input' },
              { text: 'Label', link: '/felix/components/atoms#label' },
              { text: 'Logo', link: '/felix/components/atoms#logo' },
              { text: 'Marker', link: '/felix/components/atoms#marker' },
              { text: 'Progress', link: '/felix/components/atoms#progress' },
              { text: 'RadioGroup', link: '/felix/components/atoms#radiogroup' },
              { text: 'Separator', link: '/felix/components/atoms#separator' },
              { text: 'Skeleton', link: '/felix/components/atoms#skeleton' },
              { text: 'Slider', link: '/felix/components/atoms#slider' },
              { text: 'Spinner', link: '/felix/components/atoms#spinner' },
              { text: 'Switch', link: '/felix/components/atoms#switch' },
              { text: 'Text', link: '/felix/components/atoms#text' },
              { text: 'Textarea', link: '/felix/components/atoms#textarea' }
            ] },
            { text: 'Molecules', collapsed: true, link: '/felix/components/molecules', items: [
              { text: 'Accordion', link: '/felix/components/molecules#accordion' },
              { text: 'Alert', link: '/felix/components/molecules#alert' },
              { text: 'Attachment', link: '/felix/components/molecules#attachment' },
              { text: 'Breadcrumb', link: '/felix/components/molecules#breadcrumb' },
              { text: 'Calendar', link: '/felix/components/molecules#calendar' },
              { text: 'Card', link: '/felix/components/molecules#card' },
              { text: 'ChoiceCard', link: '/felix/components/molecules#choicecard' },
              { text: 'Collapse', link: '/felix/components/molecules#collapse' },
              { text: 'DatePicker', link: '/felix/components/molecules#datepicker' },
              { text: 'Dialog', link: '/felix/components/molecules#dialog' },
              { text: 'Drawer', link: '/felix/components/molecules#drawer' },
              { text: 'DropdownMenu', link: '/felix/components/molecules#dropdownmenu' },
              { text: 'HoverCard', link: '/felix/components/molecules#hovercard' },
              { text: 'Message', link: '/felix/components/molecules#message' },
              { text: 'NavigationMenu', link: '/felix/components/molecules#navigationmenu' },
              { text: 'Pagination', link: '/felix/components/molecules#pagination' },
              { text: 'Popover', link: '/felix/components/molecules#popover' },
              { text: 'Select', link: '/felix/components/molecules#select' },
              { text: 'Sheet', link: '/felix/components/molecules#sheet' },
              { text: 'SidebarFooter', link: '/felix/components/molecules#sidebarfooter' },
              { text: 'Stepper', link: '/felix/components/molecules#stepper' },
              { text: 'Table', link: '/felix/components/molecules#table' },
              { text: 'Tabs', link: '/felix/components/molecules#tabs' },
              { text: 'Toast', link: '/felix/components/molecules#toast' },
              { text: 'Tooltip', link: '/felix/components/molecules#tooltip' }
            ] },
            { text: 'Organisms', collapsed: true, link: '/felix/components/organisms', items: [
              { text: 'MessageScroller', link: '/felix/components/organisms#messagescroller' },
              { text: 'Sidebar', link: '/felix/components/organisms#sidebar' }
            ] },
            { text: 'Bootstrap set', collapsed: true, link: '/felix/components-more', items: [
              { text: 'Buttons', link: '/felix/components-more#buttons-variants' },
              { text: 'Button groups', link: '/felix/components-more#button-groups-basic-and-sizes' },
              { text: 'Badges', link: '/felix/components-more#badges-variants' },
              { text: 'Alerts', link: '/felix/components-more#alerts-variants' },
              { text: 'Cards', link: '/felix/components-more#cards-basic-header-and-footer' },
              { text: 'Forms', link: '/felix/components-more#forms-text-inputs' },
              { text: 'Select', link: '/felix/components-more#select-variants' },
              { text: 'Checks and radios', link: '/felix/components-more#checks-and-radios' },
              { text: 'Switches', link: '/felix/components-more#switches' },
              { text: 'Range', link: '/felix/components-more#range' },
              { text: 'Nav and tabs', link: '/felix/components-more#nav-and-tabs' },
              { text: 'Pagination', link: '/felix/components-more#pagination' },
              { text: 'Breadcrumbs', link: '/felix/components-more#breadcrumbs' },
              { text: 'Language select', link: '/felix/components-more#language-select' },
              { text: 'Dropdowns', link: '/felix/components-more#dropdowns' },
              { text: 'Modals', link: '/felix/components-more#modals' },
              { text: 'Tooltips', link: '/felix/components-more#tooltips' },
              { text: 'Popovers', link: '/felix/components-more#popovers' },
              { text: 'Progress', link: '/felix/components-more#progress' },
              { text: 'Spinners', link: '/felix/components-more#spinners' },
              { text: 'List groups', link: '/felix/components-more#list-groups' },
              { text: 'Tables', link: '/felix/components-more#tables-basic-striped-and-hover' },
              { text: 'Accordion', link: '/felix/components-more#accordion' },
              { text: 'Collapse', link: '/felix/components-more#collapse' },
              { text: 'Toasts', link: '/felix/components-more#toasts' },
              { text: 'Offcanvas', link: '/felix/components-more#offcanvas' },
              { text: 'Carousel', link: '/felix/components-more#carousel' },
              { text: 'Avatars and stacks', link: '/felix/components-more#avatars-and-stacks' },
              { text: 'Placeholders and skeletons', link: '/felix/components-more#placeholders-and-skeletons' },
              { text: 'Steps and keyboard keys', link: '/felix/components-more#steps-and-keyboard-keys' },
              { text: 'Navbar', link: '/felix/components-more#navbar' }
            ] },
            { text: 'Cart summary', link: '/felix/cart-summary' },
            { text: 'Price timeline', link: '/felix/price-timeline' }
          ]
        },
        {
          text: 'Build',
          items: [
            { text: 'Design tokens', link: '/felix/tokens' },
            { text: 'Markdown', link: '/felix/markdown' },
            
            { text: 'Graphs', link: '/felix/graphs' }
          ]
        },
        { text: 'Charts', link: '/felix/components/charts', items: [{ text: '38 animated charts', link: '/felix/components/charts#animated-chart-catalog' }, { text: 'Reporting patterns', link: '/felix/components/charts#reporting-patterns' }] },
        { text: 'Examples', collapsed: false, items: [
            { text: 'Gauges', link: '/felix/gauges' },
            { text: 'Operations dashboard', link: '/felix/ops-dashboard' },
            { text: 'Waste dashboard', link: '/felix/waste-dashboard' },
            { text: 'Project dashboard', link: '/felix/project-dashboard' },
            { text: 'Forecast', link: '/felix/forecast' },
            { text: 'Order view', link: '/felix/order-view' },
            { text: 'Dashboard blocks', link: '/felix/blocks' },
            { text: 'Sales dashboard', link: '/felix/sales-dashboard' },
            { text: 'AP dashboard', link: '/felix/ap-dashboard' },
            { text: 'Log entry', link: '/felix/log-entry' },
            { text: 'Workflow operations', link: '/felix/workflow-ops' },
            { text: 'Messaging', link: '/felix/messaging' },
            { text: 'Calendar', link: '/felix/calendar' },
            { text: 'Projects', link: '/felix/projects' },
            { text: 'Dependencies', link: '/felix/dependencies' },
            { text: 'Node flow', link: '/felix/node-flow' },
            { text: 'Finance', link: '/felix/finance' },
            { text: 'Reports', link: '/felix/reports' },
            { text: 'Shipping', link: '/felix/shipping' },
            { text: 'Pricing', link: '/felix/pricing' }
          ]
        }
      ],
      '/lumen': [
        { text: 'Lumen', items: [
            { text: 'Foundations', link: '/lumen' },
        ] },
        { text: 'Components', collapsed: false, items: [
          { text: 'Overview', link: '/lumen/components' },
          
          { text: 'Buttons', link: '/lumen/components-more#buttons-variants' },
          { text: 'Button groups', link: '/lumen/components-more#button-groups-basic-and-sizes' },
          { text: 'Badges', link: '/lumen/components-more#badges-variants' },
          { text: 'Alerts', link: '/lumen/components-more#alerts-variants' },
          { text: 'Cards', link: '/lumen/components-more#cards-basic-header-and-footer' },
          { text: 'Forms', link: '/lumen/components-more#forms-text-inputs' },
          { text: 'Select', link: '/lumen/components-more#select-variants' },
          { text: 'Checks and radios', link: '/lumen/components-more#checks-and-radios' },
          { text: 'Switches', link: '/lumen/components-more#switches' },
          { text: 'Range', link: '/lumen/components-more#range' },
          { text: 'Nav and tabs', link: '/lumen/components-more#nav-and-tabs' },
          { text: 'Pagination', link: '/lumen/components-more#pagination' },
          { text: 'Breadcrumbs', link: '/lumen/components-more#breadcrumbs' },
          { text: 'Language select', link: '/lumen/components-more#language-select' },
          { text: 'Dropdowns', link: '/lumen/components-more#dropdowns' },
          { text: 'Modals', link: '/lumen/components-more#modals' },
          { text: 'Tooltips', link: '/lumen/components-more#tooltips' },
          { text: 'Popovers', link: '/lumen/components-more#popovers' },
          { text: 'Progress', link: '/lumen/components-more#progress' },
          { text: 'Spinners', link: '/lumen/components-more#spinners' },
          { text: 'List groups', link: '/lumen/components-more#list-groups' },
          { text: 'Tables', link: '/lumen/components-more#tables-basic-striped-and-hover' },
          { text: 'Accordion', link: '/lumen/components-more#accordion' },
          { text: 'Collapse', link: '/lumen/components-more#collapse' },
          { text: 'Toasts', link: '/lumen/components-more#toasts' },
          { text: 'Offcanvas', link: '/lumen/components-more#offcanvas' },
          { text: 'Carousel', link: '/lumen/components-more#carousel' },
          { text: 'Avatars and stacks', link: '/lumen/components-more#avatars-and-stacks' },
          { text: 'Placeholders and skeletons', link: '/lumen/components-more#placeholders-and-skeletons' },
          { text: 'Steps and keyboard keys', link: '/lumen/components-more#steps-and-keyboard-keys' },
          { text: 'Navbar', link: '/lumen/components-more#navbar' },
          { text: 'Cart summary', link: '/lumen/cart-summary' },
          { text: 'Price timeline', link: '/lumen/price-timeline' }
        ] },
        { text: 'Charts', link: '/lumen/charts' },
        { text: 'Examples', collapsed: false, items: [
            { text: 'Gauges', link: '/lumen/gauges' },
            { text: 'Operations dashboard', link: '/lumen/ops-dashboard' },
            { text: 'Waste dashboard', link: '/lumen/waste-dashboard' },
            { text: 'Project dashboard', link: '/lumen/project-dashboard' },
            { text: 'Forecast', link: '/lumen/forecast' },
            { text: 'Order view', link: '/lumen/order-view' },
            { text: 'Dashboard blocks', link: '/lumen/blocks' },
            { text: 'Sales dashboard', link: '/lumen/sales-dashboard' },
            { text: 'AP dashboard', link: '/lumen/ap-dashboard' },
            { text: 'Log entry', link: '/lumen/log-entry' },
            { text: 'Workflow operations', link: '/lumen/workflow-ops' },
            { text: 'Overview', link: '/lumen/overview' },
            { text: 'Traces', link: '/lumen/traces' },
            { text: 'Agents', link: '/lumen/agents' },
            { text: 'Evals', link: '/lumen/evals' },
            { text: 'Prompts', link: '/lumen/prompts' },
            { text: 'Playground', link: '/lumen/playground' },
            { text: 'Gateway', link: '/lumen/gateway' },
            { text: 'Cost & Budget', link: '/lumen/cost-budget' },
            { text: 'API Keys', link: '/lumen/api-keys' },
            { text: 'Team', link: '/lumen/team' },
            { text: 'Settings', link: '/lumen/settings' }
        ] }
      ],
      '/scopecraft': [
        { text: 'Scopecraft', items: [
            { text: 'Foundations', link: '/scopecraft' },
        ] },
        { text: 'Components', collapsed: false, items: [
          { text: 'Overview', link: '/scopecraft/components' },
          
          { text: 'Buttons', link: '/scopecraft/components-more#buttons-variants' },
          { text: 'Button groups', link: '/scopecraft/components-more#button-groups-basic-and-sizes' },
          { text: 'Badges', link: '/scopecraft/components-more#badges-variants' },
          { text: 'Alerts', link: '/scopecraft/components-more#alerts-variants' },
          { text: 'Cards', link: '/scopecraft/components-more#cards-basic-header-and-footer' },
          { text: 'Forms', link: '/scopecraft/components-more#forms-text-inputs' },
          { text: 'Select', link: '/scopecraft/components-more#select-variants' },
          { text: 'Checks and radios', link: '/scopecraft/components-more#checks-and-radios' },
          { text: 'Switches', link: '/scopecraft/components-more#switches' },
          { text: 'Range', link: '/scopecraft/components-more#range' },
          { text: 'Nav and tabs', link: '/scopecraft/components-more#nav-and-tabs' },
          { text: 'Pagination', link: '/scopecraft/components-more#pagination' },
          { text: 'Breadcrumbs', link: '/scopecraft/components-more#breadcrumbs' },
          { text: 'Language select', link: '/scopecraft/components-more#language-select' },
          { text: 'Dropdowns', link: '/scopecraft/components-more#dropdowns' },
          { text: 'Modals', link: '/scopecraft/components-more#modals' },
          { text: 'Tooltips', link: '/scopecraft/components-more#tooltips' },
          { text: 'Popovers', link: '/scopecraft/components-more#popovers' },
          { text: 'Progress', link: '/scopecraft/components-more#progress' },
          { text: 'Spinners', link: '/scopecraft/components-more#spinners' },
          { text: 'List groups', link: '/scopecraft/components-more#list-groups' },
          { text: 'Tables', link: '/scopecraft/components-more#tables-basic-striped-and-hover' },
          { text: 'Accordion', link: '/scopecraft/components-more#accordion' },
          { text: 'Collapse', link: '/scopecraft/components-more#collapse' },
          { text: 'Toasts', link: '/scopecraft/components-more#toasts' },
          { text: 'Offcanvas', link: '/scopecraft/components-more#offcanvas' },
          { text: 'Carousel', link: '/scopecraft/components-more#carousel' },
          { text: 'Avatars and stacks', link: '/scopecraft/components-more#avatars-and-stacks' },
          { text: 'Placeholders and skeletons', link: '/scopecraft/components-more#placeholders-and-skeletons' },
          { text: 'Steps and keyboard keys', link: '/scopecraft/components-more#steps-and-keyboard-keys' },
          { text: 'Navbar', link: '/scopecraft/components-more#navbar' },
          { text: 'Cart summary', link: '/scopecraft/cart-summary' },
          { text: 'Price timeline', link: '/scopecraft/price-timeline' }
        ] },
        { text: 'Charts', link: '/scopecraft/charts' },
        { text: 'Examples', collapsed: false, items: [
            { text: 'Gauges', link: '/scopecraft/gauges' },
            { text: 'Operations dashboard', link: '/scopecraft/ops-dashboard' },
            { text: 'Waste dashboard', link: '/scopecraft/waste-dashboard' },
            { text: 'Project dashboard', link: '/scopecraft/project-dashboard' },
            { text: 'Forecast', link: '/scopecraft/forecast' },
            { text: 'Order view', link: '/scopecraft/order-view' },
            { text: 'Dashboard blocks', link: '/scopecraft/blocks' },
            { text: 'Sales dashboard', link: '/scopecraft/sales-dashboard' },
            { text: 'AP dashboard', link: '/scopecraft/ap-dashboard' },
            { text: 'Log entry', link: '/scopecraft/log-entry' },
            { text: 'Workflow operations', link: '/scopecraft/workflow-ops' },
            { text: 'Dashboard', link: '/scopecraft/dashboard' },
            { text: 'Opportunities', link: '/scopecraft/opportunities' },
            { text: 'Proposals', link: '/scopecraft/proposals' },
            { text: 'Projects', link: '/scopecraft/projects' },
            { text: 'Templates library', link: '/scopecraft/templates' },
            { text: 'Rate card', link: '/scopecraft/rate-card' },
            { text: 'Settings', link: '/scopecraft/settings' }
        ] },
        { text: 'Opportunity tabs', collapsed: false, items: [
            { text: 'Overview', link: '/scopecraft/overview' },
            { text: 'Discovery', link: '/scopecraft/discovery' },
            { text: 'Scope', link: '/scopecraft/scope' },
            { text: 'Similar projects', link: '/scopecraft/similar' },
            { text: 'Estimate', link: '/scopecraft/estimate' },
            { text: 'Pricing', link: '/scopecraft/pricing-tab' },
            { text: 'Risks', link: '/scopecraft/risks' },
            { text: 'Proposal', link: '/scopecraft/proposal' },
            { text: 'SOW', link: '/scopecraft/sow' },
            { text: 'Activity', link: '/scopecraft/activity' }
        ] }
      ],
      '/pulsefit': [
        {
          text: 'PulseFit',
          items: [
            { text: 'Foundations', link: '/pulsefit' },
          ]
        },
        { text: 'Components', collapsed: false, items: [
          { text: 'Overview', link: '/pulsefit/components' },
          
          { text: 'Buttons', link: '/pulsefit/components-more#buttons-variants' },
          { text: 'Button groups', link: '/pulsefit/components-more#button-groups-basic-and-sizes' },
          { text: 'Badges', link: '/pulsefit/components-more#badges-variants' },
          { text: 'Alerts', link: '/pulsefit/components-more#alerts-variants' },
          { text: 'Cards', link: '/pulsefit/components-more#cards-basic-header-and-footer' },
          { text: 'Forms', link: '/pulsefit/components-more#forms-text-inputs' },
          { text: 'Select', link: '/pulsefit/components-more#select-variants' },
          { text: 'Checks and radios', link: '/pulsefit/components-more#checks-and-radios' },
          { text: 'Switches', link: '/pulsefit/components-more#switches' },
          { text: 'Range', link: '/pulsefit/components-more#range' },
          { text: 'Nav and tabs', link: '/pulsefit/components-more#nav-and-tabs' },
          { text: 'Pagination', link: '/pulsefit/components-more#pagination' },
          { text: 'Breadcrumbs', link: '/pulsefit/components-more#breadcrumbs' },
          { text: 'Language select', link: '/pulsefit/components-more#language-select' },
          { text: 'Dropdowns', link: '/pulsefit/components-more#dropdowns' },
          { text: 'Modals', link: '/pulsefit/components-more#modals' },
          { text: 'Tooltips', link: '/pulsefit/components-more#tooltips' },
          { text: 'Popovers', link: '/pulsefit/components-more#popovers' },
          { text: 'Progress', link: '/pulsefit/components-more#progress' },
          { text: 'Spinners', link: '/pulsefit/components-more#spinners' },
          { text: 'List groups', link: '/pulsefit/components-more#list-groups' },
          { text: 'Tables', link: '/pulsefit/components-more#tables-basic-striped-and-hover' },
          { text: 'Accordion', link: '/pulsefit/components-more#accordion' },
          { text: 'Collapse', link: '/pulsefit/components-more#collapse' },
          { text: 'Toasts', link: '/pulsefit/components-more#toasts' },
          { text: 'Offcanvas', link: '/pulsefit/components-more#offcanvas' },
          { text: 'Carousel', link: '/pulsefit/components-more#carousel' },
          { text: 'Avatars and stacks', link: '/pulsefit/components-more#avatars-and-stacks' },
          { text: 'Placeholders and skeletons', link: '/pulsefit/components-more#placeholders-and-skeletons' },
          { text: 'Steps and keyboard keys', link: '/pulsefit/components-more#steps-and-keyboard-keys' },
          { text: 'Navbar', link: '/pulsefit/components-more#navbar' },
          { text: 'Cart summary', link: '/pulsefit/cart-summary' },
          { text: 'Price timeline', link: '/pulsefit/price-timeline' },
          { text: 'KPI cards', link: '/pulsefit/kpi-cards' }
        ] },
        { text: 'Charts', link: '/pulsefit/charts', items: [{ text: '38 animated charts', link: '/pulsefit/charts#animated-chart-catalog' }, { text: 'Reporting patterns', link: '/pulsefit/charts#reporting-patterns' }] },
        { text: 'Examples', collapsed: false, items: [
            { text: 'Gauges', link: '/pulsefit/gauges' },
            { text: 'Operations dashboard', link: '/pulsefit/ops-dashboard' },
            { text: 'Waste dashboard', link: '/pulsefit/waste-dashboard' },
            { text: 'Project dashboard', link: '/pulsefit/project-dashboard' },
            { text: 'Forecast', link: '/pulsefit/forecast' },
            { text: 'Order view', link: '/pulsefit/order-view' },
            { text: 'Dashboard blocks', link: '/pulsefit/blocks' },
            { text: 'Sales dashboard', link: '/pulsefit/sales-dashboard' },
            { text: 'AP dashboard', link: '/pulsefit/ap-dashboard' },
            { text: 'Log entry', link: '/pulsefit/log-entry' },
            { text: 'Workflow operations', link: '/pulsefit/workflow-ops' },
            { text: 'Messaging', link: '/pulsefit/messaging' },
            { text: 'Calendar', link: '/pulsefit/calendar' },
            { text: 'Staff', link: '/pulsefit/staff' },
            { text: 'Projects', link: '/pulsefit/projects' },
            { text: 'Dependencies', link: '/pulsefit/dependencies' },
            { text: 'Node flow', link: '/pulsefit/node-flow' },
            { text: 'Finance', link: '/pulsefit/finance' },
            { text: 'Reports', link: '/pulsefit/reports' },
            { text: 'Shipping', link: '/pulsefit/shipping' },
            { text: 'Pricing', link: '/pulsefit/pricing' }
          ]
        }
      ],
      '/': [
      { text: 'Getting started', items: [{ text: 'Introducción', link: '/introduccion' }] },
      { text: 'Fundamentos', items: [
        { text: 'Colores', link: '/fundamentos/colores' },
        { text: 'Tipografía', link: '/fundamentos/tipografia' },
        { text: 'Iconos', link: '/fundamentos/iconos' }
      ] },
      { text: 'Full UI catalog', link: '/ui-kit' },
      { text: 'Lustro full live catalog', link: '/lustro/components' },
          
      { text: 'Lustro expanded set (52 sections)', link: '/lustro/components-more' },
      { text: 'Componentes', link: '/components', collapsed: true, items: [
        { text: 'Accordion', link: '/components#accordion' },
        { text: 'Alerts', link: '/components#alerts' },
        { text: 'Badge', link: '/components#badge' },
        { text: 'Breadcrumb', link: '/components#breadcrumb' },
        { text: 'Buttons', link: '/components#buttons' },
        { text: 'Button group', link: '/components#button-group' },
        { text: 'Card', link: '/components#card' },
        { text: 'Carousel', link: '/components#carousel' },
        { text: 'Close button', link: '/components#close-button' },
        { text: 'Collapse', link: '/components#collapse' },
        { text: 'Language select', link: '/components#language-select' },
        { text: 'Dropdowns', link: '/components#dropdowns' },
        { text: 'Forms', link: '/components#forms' },
        { text: 'List group', link: '/components#list-group' },
        { text: 'Modal', link: '/components#modal' },
        { text: 'Navbar & Footer', link: '/components#navbar-and-footer' },
        { text: 'Navs & tabs', link: '/components#navs-tabs' },
        { text: 'Offcanvas', link: '/components#offcanvas' },
        { text: 'Pagination', link: '/components#pagination' },
        { text: 'Placeholders', link: '/components#placeholders' },
        { text: 'Popovers', link: '/components#popovers' },
        { text: 'Progress', link: '/components#progress' },
        { text: 'Scrollspy', link: '/components#scrollspy' },
        { text: 'Spinners/Loaders', link: '/components#spinners-loaders' },
        { text: 'Tables', link: '/tables', collapsed: true, items: ['Basic','Striped','Hover rows','Compact','Bordered','Sticky header','Sortable','Search and column filters','Pagination','Selectable rows','Row actions','Expandable rows','Numeric columns with deltas','Footer totals','Empty state','Loading skeleton','Responsive card layout'].map(t=>({ text: t, link: '/tables#' + ({'Search and column filters':'filterable','Numeric columns with deltas':'deltas','Responsive card layout':'responsive','Hover rows':'hover'}[t]||t.toLowerCase().replace(/ /g,'-')) })) },
        { text: 'Toasts', link: '/components#toasts' },
        { text: 'Tooltips', link: '/components#tooltips' }
      ] },
      { text: 'Email templates', items: [
        { text: 'Correos transaccionales', link: '/correos' },
        { text: 'Bienvenida', link: '/correos#bienvenida' },
        { text: 'Verificar correo', link: '/correos#verificar-correo' },
        { text: 'Recuperar contraseña', link: '/correos#recuperar-contrasena' },
        { text: 'Reserva confirmada', link: '/correos#reserva-confirmada' },
        { text: 'Recordatorio de clase', link: '/correos#recordatorio-de-clase' },
        { text: 'Cupo en lista de espera', link: '/correos#cupo-en-lista-de-espera' },
        { text: 'Clase cancelada', link: '/correos#clase-cancelada' },
        { text: 'Comprobante de compra', link: '/correos#comprobante-de-compra' },
        { text: 'Membresía por vencer', link: '/correos#membresia-por-vencer' }
      ] },
      { text: 'Examples', collapsed: false, items: [
        { text: 'Messaging', link: '/messaging' },
        { text: 'Calendar', link: '/calendar' },
        { text: 'Projects', link: '/projects' },
        { text: 'Dependencies', link: '/dependencies' },
        { text: 'Node flow', link: '/node-flow' },
        { text: 'Reference collection', link: '/reference-templates' },
        { text: 'Reusable graphs', link: '/graph-components' },
        { text: 'Fixtrack maintenance', link: '/fixtrack' },
        { text: 'Folio finance', link: '/folio' },
        { text: 'Orange analytics', link: '/spark-analytics' },
        { text: 'Pulse projects', link: '/pulse-projects' },
        { text: 'Crestway financials', link: '/crestway-financials' },
        { text: 'Finance', link: '/finance' },
        { text: 'Reports', link: '/reports' },
        { text: 'Shipping', link: '/shipping' },
        { text: 'Pricing', link: '/pricing' },
        { text: 'Role examples', link: '/ejemplos/', collapsed: true, items: [
          { text: 'Introducción', link: '/ejemplos/' },
          { text: 'Users', link: '/ejemplos/users' },
          { text: 'Coaches', link: '/ejemplos/coaches' },
          { text: 'Admin', link: '/ejemplos/admin' }
        ] }
      ] },
          { text: 'Charts', link: '/graphs', collapsed: true, items: [
            { text: '38 animated charts', link: '/graphs#animated-chart-catalog' },
            { text: 'Introducción', link: '/graphs#data-charts' },
            { text: 'Line & Area', link: '/graphs#charts-line-area' },
            { text: 'Bar', link: '/graphs#charts-bar' },
            { text: 'Pie & Doughnut', link: '/graphs#charts-pie-doughnut' },
            { text: 'Radar & Polar', link: '/graphs#charts-radar-polar' },
            { text: 'Scatter & Bubble', link: '/graphs#charts-scatter-bubble' },
            { text: 'Mixed', link: '/graphs#charts-mixed' },
            { text: 'Reporting patterns', link: '/graphs#reporting-patterns' }
          ] },
          
    ]
    },
    socialLinks: [
      { icon: 'github', link: 'https://github.com/axeliodiaz/templates' }
    ]
  }
})
