<script setup lang="ts">
import { computed,ref } from 'vue'
const tab=ref('Financials'), branch=ref('Crestway'), metric=ref('EBITDA'), driver=ref('Labor'), notice=ref(''), dialog=ref<HTMLDialogElement|null>(null), draft=ref(''), selectedMonth=ref('Sep'), query=ref('')
const metrics=[['Revenue','$16.36M','0.2% below plan'],['EBITDA','$1.84M','8.4% below plan'],['Gross margin','47.2%','1.6 pts below baseline'],['Synergies','$212K','44% behind plan to date'],['Integration spend','$318K','9.7% over budget']]
const months=['Apr','May','Jun','Jul','Aug','Sep'],bars=[145,151,160,153,144,148],plans=[165,165,162]
const drivers=[['Labor',74],['Vehicle',31],['Material',28],['Revenue leakage',21],['Other',14]] as const
const issues=ref(['Technician overtime - Concord branch'])
const filtered=computed(()=>['Merritt','Crestway','Bluestem','Sawyer','Harlan','Pinecrest','Aldridge','Kessler'].filter(n=>n.toLowerCase().includes(query.value.toLowerCase())))
function save(){if(!draft.value.trim())return;issues.value.push(draft.value.trim().slice(0,100));notice.value='Issue created in this demo only. No real tracker changed.';dialog.value?.close();draft.value=''}
function create(){draft.value='Concord overtime above baseline';dialog.value?.showModal()}
const overtime=[35,37,38,36,36,39,44,63,80,85,91,95,88]
</script>
<template>
<section class="reference-dashboard crestway" aria-label="Crestway sample acquisition financials">
 <aside class="crest-rail" aria-label="Illustrative tool rail"><b>⬢</b><button v-for="(n,i) in ['Dashboard','Messages','Companies','Tasks','Reports','Documents','Notifications','Settings']" :key="n" :aria-label="n+' demo'" @click="notice=n+' is illustrative.'">{{['▦','☏','▤','☑','⌁','▧','♧','⚙'][i]}}</button><span>AD</span></aside>
 <aside class="crest-sidebar"><input v-model="query" aria-label="Search companies" placeholder="⌕ Search"/><small>⌄ FAVORITES</small><button v-for="n in ['Crestway','Merritt','Bluestem']" :key="n" @click="branch=n;notice='Sample company selected.'">☆ {{n}}</button><small>⌄ BOLT-ONS</small><div v-for="n in filtered" :key="n"><button :class="{active:branch===n}" @click="branch=n;notice=n==='Crestway'?'':n+' selected. Financial values remain illustrative.'">○ {{n}} <span v-if="n==='Crestway'">2</span></button><div v-if="n==='Crestway'" class="crest-branches"><button v-for="b in ['Charlotte HQ','Concord','Gastonia','Rock Hill']" :key="b" @click="notice=b+' branch selected. See the sample overtime report.'">□ {{b}}</button></div></div><small>⌄ PIPELINE</small><button @click="notice='Rowan Air is a sample pipeline entry.'">◌ Rowan Air</button><button @click="notice='Tolliver is a sample pipeline entry.'">◌ Tolliver</button><small>⌃ COMPLETED · 3</small><button class="crest-add" @click="notice='Add bolt-on is illustrative. No company acquired.'">＋ Add bolt-on</button></aside>
 <main class="crest-main"><header class="crest-header"><div><h2><i></i>{{branch}} Air &amp; Heat <span>● At risk</span></h2><p>└ □ Charlotte HQ / □ Concord / □ Gastonia / □ Rock Hill</p></div><button aria-label="Favorite company" @click="notice='Favorite updated in this demo.'">☆</button><button aria-label="Company menu" @click="notice='Sample company menu.'">⋮</button></header><nav class="crest-tabs" aria-label="Company views"><button v-for="n in ['Overview','Plan','Financials','Issues','People','Files','Updates']" :key="n" :class="{active:tab===n}" @click="tab=n">{{n}}<small v-if="n==='Issues'">{{issues.length}}</small><small v-if="n==='Files'">12</small><small v-if="n==='Updates'" class="red">3</small></button><span class="crest-faces">JD AM SK +4</span><button aria-label="Add sample team member" @click="notice='No invitation sent. Team control is illustrative.'">＋</button></nav>
 <template v-if="tab==='Financials'||tab==='Overview'||tab==='Plan'"><p v-if="tab!=='Financials'" class="crest-context">{{tab}} preview · Sample financials and integration performance</p><div class="crest-kpis"><button v-for="(m,i) in metrics" :key="m[0]" :class="{active:metric===m[0]}" @click="metric=m[0];notice=m[0]+' metric selected. Chart below shows EBITDA.'"><small>{{m[0]}}</small><strong>{{m[1]}}</strong><span :class="{negative:i===1||i===3,amber:i===4}">{{m[2]}}</span></button></div>
 <div class="crest-grid"><section class="crest-card crest-ebitda"><div class="ref-card-title"><h3>EBITDA by month <small>$K · dashed line is plan</small></h3><div class="crest-legend"><span><i></i>Actual</span><span><i class="gray"></i>Before close</span></div></div><div class="crest-ebitda-chart"><div class="crest-axis"><span>$180K</span><span>$120K</span><span>$60K</span><span>$0K</span></div><div class="crest-months"><button v-for="(m,i) in months" :key="m" :aria-label="m+' EBITDA '+bars[i]+' thousand dollars'" :class="{selected:selectedMonth===m,before:i<3}" @click="selectedMonth=m;notice=m+' EBITDA: $'+bars[i]+'K, sample data.'"><i :style="{height:bars[i]/1.8+'%'}"></i><span v-if="i>=3" class="crest-plan" :style="{bottom:plans[i-3]/1.8+'%'}"></span><small v-if="i>=3" class="crest-variance">{{[-9,-19,-14][i-3]}}</small><b>{{m}}</b></button></div><span class="crest-close">Closed Jun 30</span></div></section>
 <section class="crest-card crest-drivers"><div class="ref-card-title"><h3>Why is EBITDA below plan?</h3><strong>−$168K explained</strong></div><div v-for="d in drivers" :key="d[0]"><button class="crest-driver" :class="{active:driver===d[0]}" @click="driver=driver===d[0]?'':d[0]" :aria-expanded="driver===d[0]"><span>{{driver===d[0]?'⌄':'›'}} {{d[0]}}</span><i><b :style="{width:d[1]/74*100+'%'}"></b></i><strong>−${{d[1]}}K</strong></button><div v-if="driver===d[0]" class="crest-breakdown"><template v-if="d[0]==='Labor'"><div class="crest-overtime-row"><span>Technician overtime</span><i></i><b>−$58K</b></div><div><span>Duplicate payroll runs</span><b>−$9K</b></div><div><span>Onboarding and training</span><b>−$7K</b></div></template><p v-else>{{d[0]}} contributes ${{d[1]}}K to the sample variance. Illustrative accounting detail only.</p></div></div></section>
 <section class="crest-card crest-overtime"><div class="ref-card-title"><h3>Concord overtime <small>hours a week · 13 weeks</small></h3><strong>2.2× baseline</strong></div><div class="crest-overtime-chart"><div class="crest-axis"><span>100 h</span><span>50 h</span><span>0 h</span></div><div class="crest-ot-bars"><button v-for="(v,i) in overtime" :key="i" :aria-label="'Week '+(i+1)+': '+v+' overtime hours'" :style="{height:v+'%',background:i<6?'#b4b8bd':i<12?'#e38288':'#da5b72'}" @click="notice='Sample week '+(i+1)+': '+v+' overtime hours.'"></button><div class="crest-baseline"><span>Pre-close 38.5 h</span></div></div></div><div class="crest-dates"><span>Jul 5</span><span>Jul 26</span><span>Aug 16</span><span>Sep 6</span><span>Sep 27</span></div></section>
 <section class="crest-card crest-insight"><small>♧ Top driver · Concord branch</small><h3>Concord overtime has run at 2.2× its pre-close baseline for 6 weeks</h3><p>After-hours calls still run on FieldEdge dispatch, and the legacy daily overtime rule stays until the payroll cutover.</p><div class="ref-tools"><button class="ref-primary" @click="create">＋ Create issue</button><button @click="notice='Concord branch report is shown in the overtime chart.'">Open Concord</button></div></section></div></template>
 <section v-else-if="tab==='Issues'" class="crest-card crest-issue-list"><h3>Sample integration issues</h3><p v-for="(i,n) in issues" :key="n"><span>ISS-{{n+1}}</span>{{i}} <small>Open</small></p><button class="ref-primary" @click="create">＋ Create issue</button></section><section v-else class="crest-card crest-issue-list"><h3>{{tab}}</h3><p>{{tab}} is an illustrative section. No real document, person or update is connected.</p><button @click="tab='Financials'">Back to Financials</button></section>
 <p v-if="notice" class="ref-notice" role="status">{{notice}}</p><footer>Fictitious acquisition data · No real financial, payroll, company or issue action</footer></main>
 <dialog ref="dialog" class="ref-dialog"><form @submit.prevent="save"><h3>Create sample issue</h3><p>This stays in the local demo. No real tracker is connected.</p><label>Issue title<input v-model="draft" required maxlength="100" aria-label="Crestway issue title"/></label><div class="ref-tools"><button type="button" @click="dialog?.close()">Cancel</button><button class="ref-primary" :disabled="!draft.trim()">Create local issue</button></div></form></dialog>
</section>
</template>
