<script setup lang="ts">
import { computed, ref } from 'vue'
const page=ref('Dashboard'), query=ref(''), period=ref('Last 30 days'), selected=ref('Water leak · Unit 204'), contractor=ref(''), jobStatus=ref('Assigned'), notice=ref(''), message=ref(''), modal=ref<HTMLDialogElement|null>(null), modalKind=ref('Assign job'), newTitle=ref(''), priority=ref('Normal')
const requests=ref([{title:'Water leak · Unit 204',detail:'Leaking kitchen sink · reported 24 min ago',status:'Urgent'},{title:'No heat · Unit 110',detail:'Radiator inspection · reported 1 hour ago',status:'Assigned'},{title:'Sticky lock · Unit 305',detail:'Front door access · reported 3 hours ago',status:'Waiting'}])
const contractors=[{name:"Milo's Plumbing",trade:'Plumbing',price:480,eta:'18 min',rating:'96%',load:67},{name:'Northline Heating',trade:'Heating',price:520,eta:'42 min',rating:'92%',load:62},{name:'Arden Electric',trade:'Electrical',price:460,eta:'1.4 days',rating:'94%',load:80}]
const filtered=computed(()=>requests.value.filter(r=>`${r.title} ${r.detail}`.toLowerCase().includes(query.value.toLowerCase())))
const chat=ref([{text:'The leak is contained and parts are on the way.',sent:false},{text:'Thanks. Keep the tenant updated, please.',sent:true}])
function detail(title:string){selected.value=title;page.value='Request detail'}
function assign(name:string){contractor.value=name;modalKind.value='Send job';modal.value?.showModal()}
function confirm(){if(modalKind.value==='New request'){if(!newTitle.value.trim())return;requests.value.unshift({title:newTitle.value,detail:'Created in local demo · just now',status:priority.value});notice.value='Demo request added';newTitle.value=''}else if(modalKind.value==='Approve extra'){notice.value='$200 extra approved in this demo. No money moved.';jobStatus.value='In progress'}else{jobStatus.value='Assigned';page.value='Live job';notice.value=`Job sent to ${contractor.value} in this local demo.`}modal.value?.close()}
function send(){if(!message.value.trim())return;chat.value.push({text:message.value,sent:true});message.value=''}
</script>
<template>
<section class="reference-dashboard fixtrack" aria-label="Fixtrack property maintenance demo"><aside class="fix-sidebar"><strong class="fix-brand">◧ &nbsp; Fixtrack<small style="display:block">Property maintenance</small></strong><small>MAIN</small><button v-for="item in ['Dashboard','Requests','Work orders','Properties','Tenants']" :key="item" :class="{active:page===item}" @click="page=item">{{item}} <span v-if="item==='Requests'">12</span></button><small>OPERATIONS</small><button v-for="item in ['Contractors','Calendar','Reports']" :key="item" :class="{active:page===item}" @click="page=item">{{item}}</button><small>ACCOUNT</small><button @click="notice='Two unread demo messages'">Messages</button><button @click="notice='Local workspace settings. No external account connected.'">Settings</button><div class="fix-profile">◉ &nbsp; Dana Ruiz<small>demo@fixtrack.local</small></div></aside>
<main class="fix-main"><div class="fix-topbar"><input v-model="query" aria-label="Search maintenance" placeholder="Search requests, units or tenants"><span class="ref-avatar">DR</span><select v-model="period" aria-label="Maintenance period"><option>Last 30 days</option><option>Last 7 days</option></select><button @click="notice='Showing all properties. Fictitious portfolio.'">⌘ Filter</button><button class="ref-primary" @click="modalKind='New request';modal?.showModal()">+ New request</button></div><div class="fix-mobile-nav"><label>Section<select v-model="page" aria-label="Maintenance section"><option v-for="item in ['Dashboard','Requests','Work orders','Properties','Tenants','Contractors','Calendar','Reports']" :key="item">{{item}}</option></select></label></div><div class="ref-heading"><div><h2>{{page}}</h2><p>Northstar properties · Fictitious workspace</p></div><button v-if="page!=='Dashboard'" @click="page='Dashboard'">← Dashboard</button></div>
<template v-if="page==='Dashboard'"><div class="fix-kpis"><article v-for="k in [{label:'Open requests',value:period==='Last 30 days'?'28':'9',note:'↗ 12% vs last period'},{label:'Urgent',value:'5',note:'2 need contractor today'},{label:'Assigned',value:'14',note:'Active across 6 properties'},{label:'First response',value:'42 min',note:'↘ 18% faster than last month'}]" :key="k.label" class="fix-kpi"><small>{{k.label}}</small><strong>{{k.value}}</strong><p>{{k.note}}</p></article></div>
<div class="fix-grid"><article class="fix-card"><h3>REQUEST PIPELINE</h3><svg class="fix-gauge" viewBox="0 0 240 150" role="img" aria-label="28 open requests by stage"><path d="M30 115 A90 90 0 0 1 210 115" fill="none" stroke="#e6ebe5" stroke-width="20"/><path class="segments" d="M30 115 A90 90 0 0 1 171 42" fill="none" stroke="#2a5546" stroke-width="20" pathLength="100"/><path class="segments" d="M176 45 A90 90 0 0 1 210 115" fill="none" stroke="#e5634d" stroke-width="20" pathLength="100"/><text x="120" y="102" text-anchor="middle" font-size="28" font-weight="700">28</text><text x="120" y="123" text-anchor="middle" font-size="11">Open requests</text></svg><div class="fix-legend"><span><i class="fix-dot"></i>New · 8 received today</span><span><i class="fix-dot"></i>Assigned · 14 contractors booked</span><span><i class="fix-dot orange"></i>In progress · 5 technicians on site</span><span><i class="fix-dot orange"></i>Waiting · 1 needs approval</span></div></article>
<article class="fix-card"><h3>FIRST RESPONSE TIME <span style="float:right;font-size:9px">All properties · 2026</span></h3><strong style="font-size:27px;display:block;margin:15px 0 0">42 min <small style="font-size:9px" class="ref-positive">↓ 18% faster</small></strong><svg class="fix-chart" viewBox="0 0 450 180" role="img" aria-label="Response time falls from January to June"><g stroke="#e8ece7"><path d="M20 35H430M20 75H430M20 115H430M20 155H430"/></g><rect x="260" y="15" width="70" height="150" rx="8" fill="#e0ece4"/><path class="ref-line" d="M20 36 C60 36 90 70 110 70 S175 82 200 84 S280 104 310 115 S385 127 430 145" stroke="#477568" fill="none" stroke-width="2"/><g fill="#477568"><circle v-for="(p,i) in [[20,36],[110,70],[200,84],[310,115],[430,145]]" :key="i" :cx="p[0]" :cy="p[1]" r="3"/></g></svg><div class="fix-labels"><span v-for="m in ['Jan','Feb','Mar','Apr','May','Jun']" :key="m">{{m}}</span></div></article></div>
<div class="fix-bottom"><article class="fix-card"><h3>NEEDS ATTENTION</h3><div v-for="r in filtered" :key="r.title" class="fix-request"><button @click="detail(r.title)">◉ &nbsp;{{r.title}}<small>{{r.detail}}</small></button><span class="fix-badge" :class="{urgent:r.status==='Urgent'}">{{r.status}}</span></div><p v-if="!filtered.length">No matching requests.</p><button style="width:100%;font-size:9px;margin-top:10px" @click="page='Requests'">View all flagged requests →</button></article><article class="fix-card"><h3>TODAY'S SCHEDULE</h3><strong style="font-size:22px;display:block;margin-top:12px">10 <small style="font-size:9px">appointments</small></strong><div class="fix-bars"><button v-for="(h,i) in [70,50,93,33]" :key="i" :style="{height:h+'%'}" :aria-label="'View '+['9-12','12-15','15-18','18-21'][i]+' schedule'" @click="page='Calendar';notice='Schedule selected for '+['9-12','12-15','15-18','18-21'][i]"><span>{{['9–12','12–15','15–18','18–21'][i]}}</span></button></div></article><article class="fix-card"><h3>CONTRACTOR LOAD</h3><p style="margin-top:15px">6 active today</p><div v-for="c in contractors" :key="c.name" class="fix-contractor"><div><button style="border:0;padding:0;font-size:9px" @click="page='Contractors'">{{c.name}}</button><span>{{c.load}}%</span></div><div class="fix-load" :class="{red:c.load>=80}"><i :style="{width:c.load+'%'}"></i></div></div></article></div></template>
<template v-else-if="page==='Request detail'"><div class="ref-heading"><div><h3>{{selected}}</h3><p>REQ-204 · Oak Grove · Kitchen sink · Urgent</p></div><button class="ref-primary" @click="page='Assign a contractor'">Assign contractor →</button></div><div class="fix-detail-grid"><article class="fix-card fix-summary"><h3>TENANT REPORT</h3><p>"Water is leaking underneath the kitchen sink. It started this morning and is getting worse. I have put a bucket underneath, but the cabinet is still wet."</p><small>Sam Miller · Unit 204 · 24 minutes ago</small><div class="fix-photos"><div class="fix-photo" role="img" aria-label="Illustrative sink">▱</div><div class="fix-photo" role="img" aria-label="Illustrative pipe">◉</div><div class="fix-photo" role="img" aria-label="Illustrative cabinet">▤</div></div><div class="fix-ai"><h3>✦ Suggested next steps</h3><p>Plumbing issue. Shut off the sink supply, protect the cabinet and book an available plumber. This suggestion is sample text, not a live AI diagnosis.</p><button @click="page='Assign a contractor'">Assign a plumber</button></div></article><article class="fix-card"><h3>REQUEST SUMMARY</h3><p style="margin:15px 0">Property: Oak Grove<br>Unit: 204<br>Priority: Urgent<br>Category: Plumbing<br>Status: {{jobStatus}}</p><h3>ACTIVITY</h3><p style="margin:15px 0">Report received<br>Photos attached<br>Team notified</p></article></div></template>
<template v-else-if="page==='Assign a contractor'||page==='Contractors'"><h3>Assign a contractor</h3><p style="margin:10px 0">Compare availability, response time and sample quotes.</p><div class="fix-detail-grid"><article class="fix-card"><div v-for="c in contractors" :key="c.name" class="fix-assignment"><span><b>{{c.name}}</b><small>{{c.trade}} · ETA {{c.eta}} · {{c.rating}} satisfaction</small></span><b>${{c.price}}</b><button class="ref-primary" @click="assign(c.name)">Assign</button></div></article><article class="fix-card"><h3>{{selected}}</h3><p style="margin:15px 0">Water leak · Unit 204<br>Urgent · Plumbing<br>Estimated budget $450–600</p><div class="fix-ai"><h3>Best match</h3><p>Milo's Plumbing: 18 minute ETA, 96% satisfaction. Fictitious recommendation.</p></div></article></div></template>
<template v-else-if="page==='Live job'||page==='Work orders'"><div class="ref-heading"><div><h3>Live job</h3><p>{{selected}} · {{contractor||"Milo's Plumbing"}} · ${{contractors.find(c=>c.name===contractor)?.price||480}}</p></div><select v-model="jobStatus" aria-label="Demo job status"><option>Assigned</option><option>Accepted</option><option>On the way</option><option>In progress</option><option>Completed</option></select></div><div class="fix-track"><span v-for="(s,i) in ['Assigned','Accepted','On the way','In progress','Completed']" :key="s" :class="{done:i<=['Assigned','Accepted','On the way','In progress','Completed'].indexOf(jobStatus)}">{{s}}</span></div><div class="fix-detail-grid"><article class="fix-card"><h3>JOB UPDATES</h3><div class="fix-chat"><div v-for="(m,i) in chat" :key="i" class="fix-message" :class="{sent:m.sent}">{{m.text}}</div></div><form class="fix-chat-form" @submit.prevent="send"><input v-model="message" placeholder="Message contractor" aria-label="Message contractor"><button type="submit">Send</button></form></article><article class="fix-card"><h3>ADDITIONAL WORK</h3><p style="margin:15px 0">The trap fitting needs replacement. Sample extra cost: $200.</p><button class="ref-primary" @click="modalKind='Approve extra';modal?.showModal()">Approve $200 extra</button><p style="margin-top:15px">No real job, contractor message or payment is created.</p></article></div></template>
<template v-else><article class="fix-card"><h3>{{page}}</h3><p style="margin:15px 0">{{page==='Calendar'?'Today: 10 appointments across Oak Grove, Pine Court and Riverside.':page==='Properties'?'Oak Grove · 24 units; Pine Court · 18 units; Riverside · 32 units.':page==='Tenants'?'Sam Miller · Unit 204; Jordan Lee · Unit 110; Casey Lane · Unit 305.':page==='Reports'?'42 minute first response, 96% satisfaction, 28 open requests.':'Open maintenance requests'}}</p><div v-if="page==='Requests'" v-for="r in filtered" :key="r.title" class="fix-request"><button @click="detail(r.title)">{{r.title}}<small>{{r.detail}}</small></button><span class="fix-badge">{{r.status}}</span></div></article></template>
<p v-if="notice" class="ref-notice" role="status">{{notice}}</p><p style="font-size:9px;margin-top:18px">Fictitious data · Local interaction only · No contractor or bank connected.</p></main>
<dialog ref="modal" class="ref-dialog"><form @submit.prevent="confirm"><h3>{{modalKind}}</h3><template v-if="modalKind==='New request'"><label>Request title<input v-model="newTitle" required></label><label>Priority<select v-model="priority"><option>Normal</option><option>Urgent</option></select></label></template><p v-else style="margin:15px 0">{{modalKind==='Approve extra'?'Approve an illustrative $200 addition to this job?':`Send the sample job to ${contractor}? Quote: $${contractors.find(c=>c.name===contractor)?.price||480}. No real message is sent.`}}</p><div class="ref-tools"><button type="button" @click="modal?.close()">Cancel</button><button class="ref-primary" type="submit">{{modalKind==='New request'?'Add demo request':'Confirm demo'}}</button></div></form></dialog></section>
</template>
