<script setup lang="ts">
import { computed, ref } from 'vue'
const query=ref(''), filter=ref('All'), period=ref('This month'), tab=ref('Overview'), notice=ref(''), selected=ref('')
const dialog=ref<HTMLDialogElement|null>(null), payee=ref('Team payroll'), amount=ref('48250')
const rows=ref([{name:'Linear',sub:'Software subscription',category:'Software',status:'Completed',amount:-240,date:'Today, 10:42 AM',icon:'L'},{name:'Figma',sub:'Invoice #INV-0248',category:'Client payment',status:'Completed',amount:12500,date:'Today, 9:15 AM',icon:'F'},{name:'October payroll',sub:'24 team members',category:'Payroll',status:'Approved',amount:-48250,date:'Oct 24, 2026',icon:'◎'},{name:'Cloud hosting',sub:'Infrastructure',category:'Infrastructure',status:'Completed',amount:-1248,date:'Oct 23, 2026',icon:'☁'}])
const visible=computed(()=>rows.value.filter(r=>(filter.value==='All'||r.status===filter.value)&&`${r.name} ${r.category}`.toLowerCase().includes(query.value.toLowerCase())))
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)
function exportRows(){const csv='Transaction,Category,Status,Amount\n'+visible.value.map(r=>[r.name,r.category,r.status,r.amount].join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='folio-demo.csv';a.click();URL.revokeObjectURL(a.href);notice.value='Demo CSV exported'}
function pay(){if(!payee.value.trim()||!Number.isFinite(Number(amount.value))||Number(amount.value)<=0)return;rows.value.unshift({name:payee.value,sub:'Local demo payment',category:'Payment',status:'Approved',amount:-Number(amount.value),date:'Just now',icon:'↗'});dialog.value?.close();notice.value='Demo payment added. No money moved.'}
</script>
<template>
<section class="reference-dashboard folio" aria-label="Folio finance dashboard demo">
<header class="folio-header"><strong class="folio-brand">f. &nbsp; folio</strong><span class="folio-workspace">◩ &nbsp; Northstar Studio⌄</span><button aria-label="Show notifications" @click="notice='All caught up. No new notifications.'">♧</button><span class="ref-avatar">JD</span></header>
<nav class="folio-nav" aria-label="Finance sections"><button v-for="item in ['Overview','Transactions','Payments','Payroll','Accounts']" :key="item" :class="{active:tab===item}" @click="tab=item">{{item}} <small v-if="item==='Payments'">3</small></button><button class="folio-support" @click="notice='Demo support: contact your workspace admin.'">ⓘ &nbsp; Help & support ↗</button></nav>
<div class="folio-content"><div class="ref-heading"><div><h2>{{tab==='Overview'?'Your finances, at a glance.':tab}}</h2><p>A clear picture of where you stand and what's next.</p></div><button class="ref-primary" @click="dialog?.showModal()">+ &nbsp; Make a payment</button></div>
<div v-if="tab==='Overview'||tab==='Accounts'" class="folio-overview"><article class="folio-balance"><div class="ref-card-title">Available balance <span>↗</span></div><div class="folio-amount">$128,450<span>.80</span><small>USD</small></div><p class="ref-positive">↗ 12.8% <span>vs. last month</span></p><svg viewBox="0 0 400 110" role="img" aria-label="Balance trending upward"><defs><linearGradient id="folio-fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#a6d5c3" stop-opacity=".18"/><stop offset="1" stop-color="#a6d5c3" stop-opacity="0"/></linearGradient></defs><path d="M0 95 Q20 75 40 82 T80 68 T120 57 T160 53 T200 46 T240 40 T280 27 T320 21 T360 15 L400 0 V110 H0Z" fill="url(#folio-fill)"/><path class="ref-line" d="M0 95 Q20 75 40 82 T80 68 T120 57 T160 53 T200 46 T240 40 T280 27 T320 21 T360 15 L400 0" fill="none" stroke="#a6d5c3" stroke-width="2.5"/></svg><div class="folio-foot"><span>▥ &nbsp; 3 connected accounts</span><button @click="selected='Accounts: Operating $96,450.80 · Savings $24,000 · Reserve $8,000'">View accounts →</button></div></article>
<article class="folio-cash"><div class="ref-card-title">Monthly cash flow<select v-model="period" aria-label="Cash-flow period"><option>This month</option><option>Last month</option></select></div><div class="folio-totals"><div><small>Received</small><strong>{{period==='This month'?'$86,250':'$78,200'}}</strong></div><div><small>Spent</small><strong>{{period==='This month'?'$64,820':'$61,100'}}</strong></div></div><p>Where your money went</p><div class="folio-stack" aria-label="Payroll 74%, Operations 18%, Growth 8%"><i style="width:74%;background:#aa89d0"></i><i style="width:18%;background:#72b49b"></i><i style="width:8%;background:#d6b16c"></i></div><div class="folio-legend"><span>🟪 Payroll &nbsp;74%</span><span>🟩 Operations &nbsp;18%</span><span>🟨 Growth &nbsp;8%</span></div><div class="folio-foot"><span>Net cash flow</span><strong class="ref-positive">{{period==='This month'?'+$21,430':'+$17,100'}}</strong></div></article>
<article class="folio-payments"><div class="ref-card-title">Upcoming payments</div><p>Employee payroll<small>Oct 28 · 24 employees</small></p><strong class="folio-payroll">$48,250</strong><div class="folio-approved">✓ <span>Payroll approved</span></div><div class="folio-service"><span>Software & services<small>Oct 26 · 2 payments</small></span><b>$1,890</b></div><button @click="tab='Payments'">View all payments →</button></article></div>
<div v-if="tab==='Payments'||tab==='Payroll'" class="folio-payment-list"><h3>{{tab==='Payroll'?'Team payroll':'Upcoming payments'}}</h3><p>Employee payroll · Oct 28 · $48,250 · Approved</p><p>Software & services · Oct 26 · $1,890 · Scheduled</p><p>Office rent · Nov 1 · $8,500 · Scheduled</p><button @click="dialog?.showModal()">Add demo payment</button></div>
<div class="ref-heading folio-table-head"><div><h3>Money in motion</h3><p>Sample transactions with fictitious data</p></div><div class="ref-tools"><input v-model="query" placeholder="Find a transaction" aria-label="Find a transaction"><select v-model="filter" aria-label="Filter transactions"><option>All</option><option>Completed</option><option>Approved</option></select><button @click="exportRows">↓ Export</button></div></div>
<div class="ref-table-scroll"><table><thead><tr><th>Transaction</th><th>Category</th><th>Date</th><th>Status</th><th class="number">Amount</th><th></th></tr></thead><tbody><tr v-for="row in visible" :key="row.name+row.date"><td><div class="folio-company"><span class="folio-icon">{{row.icon}}</span><span>{{row.name}}<small>{{row.sub}}</small></span></div></td><td><span class="folio-tag">{{row.category}}</span></td><td>{{row.date}}</td><td :class="row.status==='Approved'?'ref-amber':'ref-positive'">{{row.status}}</td><td class="number" :class="{'ref-positive':row.amount>0}">{{row.amount>0?'+':''}}{{money(row.amount)}}</td><td><button :aria-label="'View '+row.name" @click="selected=`${row.name}: ${money(row.amount)} · ${row.status}`">•••</button></td></tr><tr v-if="!visible.length"><td colspan="6">No matching transactions.</td></tr></tbody></table></div><div class="folio-foot"><small>Showing {{visible.length}} transactions</small><button @click="query='';filter='All';tab='Transactions'">All transactions →</button></div><p v-if="selected" class="ref-notice">{{selected}} <button @click="selected=''" aria-label="Close details">×</button></p><p role="status" class="ref-notice" v-if="notice">{{notice}}</p><footer class="folio-footer"><b>f.</b><span>A clear head starts with clear finances.</span><small>Fictitious demo · No bank connected</small></footer></div>
<dialog ref="dialog" class="ref-dialog folio-dialog"><form @submit.prevent="pay"><h3>Make a demo payment</h3><p>No money will move. This adds a local example row.</p><label>Payee<input v-model="payee" required></label><label>Amount (USD)<input v-model="amount" type="number" min=".01" step=".01" required></label><div class="ref-tools"><button type="button" @click="dialog?.close()">Cancel</button><button class="ref-primary" type="submit">Add demo payment</button></div></form></dialog>
</section>
</template>
