<script setup lang="ts">
import { computed, ref } from 'vue'
const query=ref(''), status=ref('All statuses'), period=ref('This week'), section=ref('Home'), notice=ref(''), dialog=ref<HTMLDialogElement|null>(null), action=ref(''), title=ref(''), selected=ref<number|null>(null)
const projects=ref([
 {name:'Website Redesign',desc:'Redesign the company website',icon:'◎',status:'On Track',progress:78,deadline:'May 10, 2026',color:'#8471e8'},
 {name:'Mobile App',desc:'iOS & Android application',icon:'▣',status:'In Progress',progress:56,deadline:'May 18, 2026',color:'#68a1de'},
 {name:'Brand Campaign',desc:'Q2 marketing campaign',icon:'⚑',status:'At Risk',progress:34,deadline:'May 25, 2026',color:'#e291a8'},
 {name:'Product Launch',desc:'New feature release',icon:'♧',status:'On Track',progress:91,deadline:'Jun 2, 2026',color:'#4bbf9f'},
 {name:'Analytics Dashboard',desc:'Data visualization tool',icon:'▥',status:'Completed',progress:100,deadline:'Apr 28, 2026',color:'#9478e4'}
])
const activity=ref([{name:'Sophia Carter',text:'completed task “UI Design”',time:'2h ago'},{name:'James Wilson',text:'commented on “Mobile App”',time:'4h ago'},{name:'Emma Davis',text:'uploaded 3 new files',time:'6h ago'},{name:'Liam Brown',text:'moved task to “In Progress”',time:'8h ago'},{name:'Ava Martinez',text:'created project “Brand Campaign”',time:'12h ago'}])
const filtered=computed(()=>projects.value.map((p,i)=>({...p,i})).filter(p=>(status.value==='All statuses'||p.status===status.value)&&`${p.name} ${p.desc}`.toLowerCase().includes(query.value.toLowerCase())))
const current=computed(()=>selected.value===null?null:projects.value[selected.value])
const metrics=[['♧','Total Projects','12','20%','#8064eb'],['✓','Completed Tasks','86','12%','#36b68e'],['♧','Team Members','8','8%','#529ad8'],['◷','Avg. Delivery Time','2.4 days','18%','#c461ce']]
const curve=(n:number)=>[7,10,8,12,18,14,27,22,25,19,32,26,30,36].map((v,i)=>`${i?'L':'M'}${i*9} ${52-v-n}`).join(' ')
const performance=computed(()=>period.value==='This week'?[24,29,35,33,46,52,50,65,61,78]:[19,24,28,25,35,32,38,42,36,44])
const line=(a:number[])=>a.map((v,i)=>`${i?'L':'M'}${i*60} ${155-v*1.4}`).join(' ')
function open(kind:string){action.value=kind;title.value='';dialog.value?.showModal()}
function save(){if(!title.value.trim())return;const text=title.value.trim().slice(0,70);if(action.value==='New Project'){projects.value.push({name:text,desc:'Local sample project',icon:'▥',status:'On Track',progress:0,deadline:'No date',color:'#8471e8'});query.value='';status.value='All statuses'}else activity.value.unshift({name:'Olivia Bennett',text:action.value==='Add Task'?`created sample task “${text}”`:`prepared a demo invitation for ${text}`,time:'Just now'});notice.value=action.value==='Invite Team'?'Demo invitation only. No message was sent.':`${action.value} saved in this demo only.`;dialog.value?.close()}
function update(){if(!current.value)return;notice.value='Project updated locally. No real workspace changed.'}
</script>
<template>
<section class="reference-dashboard pulseboard" aria-label="Pulse fictitious project dashboard">
 <aside class="pulse-sidebar"><b class="pulse-brand"><span>❖</span> Pulse</b><nav aria-label="Pulse demo navigation"><button v-for="(n,i) in ['Home','Projects','Tasks','Team','Reports','Calendar','Settings']" :key="n" :class="{active:section===n}" @click="section=n;notice=n==='Home'?'':`${n} selected. Use the dashboard controls below; this is a local demo.`"><span>{{['⌂','▢','☑','♧','▥','▦','⚙'][i]}}</span>{{n}}</button></nav><small>MY WORKSPACE</small><button v-for="n in ['Marketing','Design','Development','Product']" :key="n" @click="notice=`${n} workspace is illustrative.`">◉ {{n}}</button><div class="pulse-upgrade"><b>✦</b><strong>Upgrade to Pro</strong><p>Get more insights, advanced analytics and team features.</p><button class="ref-primary" @click="notice='Upgrade is illustrative. No subscription or purchase.'">Upgrade Now →</button></div><div class="pulse-profile"><span class="pulse-avatar">OB</span><div><strong>Olivia Bennett</strong><small>Product Designer</small></div><button aria-label="Demo settings" @click="notice='Settings are illustrative.'">⚙</button></div></aside>
 <main class="pulse-main"><header class="pulse-top"><input v-model="query" aria-label="Search Pulse projects" placeholder="⌕  Search projects, tasks, or people…"/><button aria-label="Demo notifications" @click="notice='No new notifications in this demo.'">♧<i></i></button><span class="pulse-avatar">OB</span><div><strong>Olivia Bennett</strong><small>Product Designer</small></div></header>
 <div class="pulse-mobile-nav"><select v-model="section" aria-label="Pulse section"><option v-for="n in ['Home','Projects','Tasks','Team','Reports','Calendar','Settings']" :key="n">{{n}}</option></select></div>
 <div class="pulse-layout"><section class="pulse-left"><div class="ref-heading"><div><h2>Good morning, Olivia <span>☀</span></h2><p>Here's what's happening with your projects today.</p></div><select v-model="period" aria-label="Pulse reporting period"><option>This week</option><option>Last week</option></select></div><div class="pulse-kpis"><article class="pulse-kpi" v-for="(m,i) in metrics" :key="m[1]" :style="{'--pc':m[4]}"><div><span class="pulse-icon">{{m[0]}}</span><small>{{m[1]}}</small></div><strong>{{m[2]}}</strong><p> {{i===3?'↓':'↑'}} {{m[3]}}<small>vs. last 7 days</small></p><svg viewBox="0 0 125 56" role="img" :aria-label="`${m[1]} sample trend`"><path class="pulse-draw" :d="curve(i)" fill="none" :stroke="m[4]" stroke-width="1.8"/><circle cx="117" :cy="16-i" r="2" :fill="m[4]"/></svg></article></div></section>
 <section class="pulse-card pulse-health"><div class="ref-card-title"><h3>Project Health</h3><button @click="status='All statuses';notice='Showing all sample projects.'">View all →</button></div><div class="pulse-health-body"><svg viewBox="0 0 130 130" role="img" aria-label="78 percent on track"><circle cx="65" cy="65" r="47" fill="none" stroke="#e5ddfa" stroke-width="11"/><circle class="pulse-ring" cx="65" cy="65" r="47" fill="none" stroke="#8260ec" stroke-width="11" stroke-linecap="round" stroke-dasharray="230 296" transform="rotate(-90 65 65)"/><text x="65" y="65" text-anchor="middle" class="pulse-ring-value">78%</text><text x="65" y="83" text-anchor="middle">On Track</text></svg><div class="pulse-health-legend"><span><i class="green"></i>On Track <b>9</b></span><span><i class="amber"></i>At Risk <b>2</b></span><span><i class="rose"></i>Delayed <b>1</b></span></div></div></section>
 <section class="pulse-card pulse-projects"><div class="ref-card-title"><h3>Active Projects</h3><select v-model="status" aria-label="Pulse project status"><option>All statuses</option><option>On Track</option><option>In Progress</option><option>At Risk</option><option>Completed</option></select></div><div class="ref-table-scroll"><table><thead><tr><th>Project</th><th>Status</th><th>Progress</th><th>Deadline</th><th></th></tr></thead><tbody><tr v-for="p in filtered" :key="p.name"><td><button class="pulse-project-name" @click="selected=p.i"><span class="pulse-icon" :style="{'--pc':p.color}">{{p.icon}}</span><span><strong>{{p.name}}</strong><small>{{p.desc}}</small></span></button></td><td><span class="pulse-badge" :class="p.status.toLowerCase().replace(' ','-')">{{p.status}}</span></td><td><div class="pulse-progress"><span><i :style="{width:p.progress+'%',background:p.color}"></i></span><b>{{p.progress}}%</b></div></td><td>{{p.deadline}}</td><td><button :aria-label="`Details for ${p.name}`" @click="selected=p.i">···</button></td></tr><tr v-if="!filtered.length"><td colspan="5">No sample projects match.</td></tr></tbody></table></div></section>
 <section class="pulse-card pulse-activity"><div class="ref-card-title"><h3>Recent Activity</h3><button @click="notice='All sample activity is shown below.'">View all →</button></div><div v-for="(a,i) in activity.slice(0,5)" :key="a.text" class="pulse-activity-row"><span class="pulse-avatar" :style="{background:['#e3dce9','#d5e4f3','#f3dfce','#e4e3d6','#ead8e1'][i]}">{{a.name.split(' ').map(n=>n[0]).join('')}}</span><div><strong>{{a.name}}</strong><small><i></i>{{a.text}}</small></div><time>{{a.time}}</time></div></section>
 <section class="pulse-card pulse-performance"><div class="ref-card-title"><h3>Performance Overview</h3><div class="pulse-line-legend"><span>━ {{period}}</span><small>━ Comparison</small></div></div><div class="pulse-performance-body"><div class="pulse-axis"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><svg viewBox="0 0 550 170" role="img" aria-label="Sample weekly project performance"><defs><linearGradient id="pulse-fill" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#a68fe9" stop-opacity=".2"/><stop offset="1" stop-color="#a68fe9" stop-opacity="0"/></linearGradient></defs><path :d="line(performance)+' L540 165 L0 165 Z'" fill="url(#pulse-fill)"/><path class="pulse-draw" :d="line(performance)" fill="none" stroke="#9681e0" stroke-width="2"/><path class="pulse-draw" :d="line([13,18,17,21,26,22,30,34,28,39])" fill="none" stroke="#c7d6ee" stroke-width="1.5"/><circle cx="540" :cy="155-performance[9]*1.4" r="3" fill="#8064eb"/></svg><div class="pulse-chart-tip"><small>May 4</small><strong>{{performance[9]}}% <span>↑</span></strong></div></div><div class="pulse-days"><span v-for="d in ['Apr 28','Apr 29','Apr 30','May 1','May 2','May 3','May 4']" :key="d">{{d}}</span></div></section>
 <section class="pulse-card pulse-actions"><h3>Quick Actions</h3><div><button v-for="(a,i) in ['New Project','Add Task','Invite Team','View Reports']" :key="a" :class="`action-${i}`" @click="a==='View Reports'?(section='Reports',notice='Showing the sample performance report.'):open(a)"><span>{{['⊕','☑','♧','▥'][i]}}</span><strong>{{a}}</strong><small>{{['Create a new project','Assign and track','Collaborate together','See detailed insights'][i]}}</small></button></div></section>
 </div><section v-if="current" class="pulse-card pulse-detail"><div class="ref-card-title"><h3>{{current.name}}</h3><button @click="selected=null">Close details</button></div><p>Sample project. Changes reset on reload.</p><div class="ref-tools"><label>Status<select v-model="current.status" @change="update"><option>On Track</option><option>In Progress</option><option>At Risk</option><option>Completed</option></select></label><label>Progress <input type="range" min="0" max="100" v-model.number="current.progress" @input="update" aria-label="Project completion"/></label><strong>{{current.progress}}%</strong></div></section><p v-if="notice" class="ref-notice" role="status">{{notice}}</p><footer>Fictitious data · Local demo only · No real project, task, invitation or subscription is created</footer>
 </main><dialog ref="dialog" class="ref-dialog"><form @submit.prevent="save"><h3>{{action}}</h3><p>{{action==='Invite Team'?'Prepare a sample invitation. No message will be sent.':'Create a local sample. It resets on reload.'}}</p><label>{{action==='Invite Team'?'Name for demo invitation':'Title'}}<input v-model="title" required maxlength="70" aria-label="Pulse demo title"/></label><div class="ref-tools"><button type="button" @click="dialog?.close()">Cancel</button><button class="ref-primary" :disabled="!title.trim()">Save demo</button></div></form></dialog>
</section>
</template>
