<script setup lang="ts">
import{ref}from'vue'
defineProps<{theme:'folio'|'spark'|'lustro'|'felix'|'pulsefit'|'scopecraft'|'lumen'}>()
const list=ref([{id:1,title:'Monthly report'},{id:2,title:'Team review'},{id:3,title:'Forecast'}])
const cards=ref([{id:1,title:'Monthly report',state:0},{id:2,title:'Team review',state:1},{id:3,title:'Forecast',state:0}]),expanded=ref(false),replay=ref(0),status=ref('Pending')
function advance(id:number){const c=cards.value.find(c=>c.id===id);if(c)c.state=Math.min(2,c.state+1)}
</script>
<template><div :class="['studio-kit',`studio-${theme}`]"><div class="studio-grid">
<article class="sk-wide"><h3>Persistent cards between states</h3><div class="sk-motion-board"><div class="sk-board-labels"><b>Pending</b><b>Review</b><b>Complete</b></div><article v-for="c in cards" :key="c.id" class="sk-motion-card" :style="{left:`calc(${c.state} * 33.333% + 5px)`,top:(50+cards.filter(x=>x.state===c.state).findIndex(x=>x.id===c.id)*115)+'px'}"><strong>{{c.title}}</strong><small>{{['Pending','Review','Complete'][c.state]}}</small><button :disabled="c.state===2" @click="advance(c.id)">{{c.state===2?'Complete':'Advance'}}</button></article></div><button @click="cards.forEach(c=>c.state=0)">Reset board</button></article>
<article><h3>Status transition</h3><div class="studio-row"><button v-for="s in ['Pending','Review','Complete']" :key="s" :aria-pressed="status===s" @click="status=s">{{s}}</button></div><Transition name="sk-fade" mode="out-in"><span :key="status" :class="['sk-badge',status==='Complete'?'success':status==='Review'?'warning':'info']" role="status">{{status}}</span></Transition></article>
<article><h3>Expand a card</h3><button :aria-expanded="expanded" @click="expanded=!expanded">{{expanded?'Hide details':'Show details'}}</button><div class="sk-motion-expand" :class="{open:expanded}" :inert="!expanded"><div><p>Revenue sample: $12,400. Motion opens room for context; no payment or outside action.</p></div></div></article>
<article><h3>Reorder and add items</h3><div class="studio-row"><button @click="list.reverse()">Reverse list</button><button @click="list.push({id:Math.max(0,...list.map(c=>c.id))+1,title:'New local report'})">Add report</button></div><TransitionGroup name="sk-list" tag="ul" class="sk-motion-list"><li v-for="c in list" :key="c.id">{{c.title}}<button :aria-label="'Remove '+c.title" @click="list=list.filter(x=>x.id!==c.id)">×</button></li></TransitionGroup></article>
<article><h3>Staggered entry</h3><button @click="replay++">Replay entry</button><div :key="replay" class="sk-entry-list"><div v-for="(s,i) in ['Summary','Transactions','Forecast']" :key="s" class="sk-card" :style="{animationDelay:i*70+'ms'}">{{s}}</div></div></article>
</div><p>300ms card movement, 240ms expansion/reorder, 200ms state entry with 70ms stagger. Reduced motion keeps final states with zero animation. All actions stay local.</p></div></template>
<style scoped>
.sk-motion-board{position:relative;height:400px;min-width:0;border:1px solid var(--sk-border);border-radius:8px;margin:15px 0;background:repeating-linear-gradient(90deg,transparent 0,transparent calc(33.333% - 1px),var(--sk-border) calc(33.333% - 1px),var(--sk-border) 33.333%)}.sk-board-labels{display:grid;grid-template-columns:repeat(3,1fr);padding:12px;font-size:11px}.sk-motion-card{position:absolute;width:calc(33.333% - 10px);padding:12px;background:var(--sk-surface);border:1px solid var(--sk-border);border-radius:8px;transition:left .3s,top .3s;min-height:105px}.sk-motion-card strong{font-size:12px;display:block}.sk-motion-card button{padding:5px;font-size:11px;margin-top:7px}.sk-motion-expand{display:grid;grid-template-rows:0fr;opacity:0;transition:grid-template-rows .24s,opacity .24s}.sk-motion-expand.open{grid-template-rows:1fr;opacity:1}.sk-motion-expand>div{overflow:hidden}.sk-motion-list{padding:0;list-style:none}.sk-motion-list li{position:relative;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:10px;background:var(--sk-surface);margin:8px 0;border-radius:6px}.sk-list-move,.sk-list-enter-active,.sk-list-leave-active{transition:transform .24s,opacity .24s}.sk-list-enter-from,.sk-list-leave-to{opacity:0;transform:translateX(12px)}.sk-list-leave-active{position:absolute}.sk-entry-list .sk-card{margin-top:10px;animation:studio-stagger .2s both}@keyframes studio-stagger{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>
