<script setup lang="ts">
import {ref,computed,onMounted,onBeforeUnmount} from 'vue'
const props=defineProps<{theme:'folio'|'spark'}>()
const activeSection=ref('Summary'),spyRoot=ref<HTMLElement|null>(null);let spy:IntersectionObserver|undefined
onMounted(()=>{spy=new IntersectionObserver(es=>{const top=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(top)activeSection.value=top.target.getAttribute('data-spy')||'Summary'},{root:spyRoot.value,threshold:[0,.5,1]});spyRoot.value?.querySelectorAll('[data-spy]').forEach(e=>spy?.observe(e))});onBeforeUnmount(()=>spy?.disconnect())
const notice=ref(''),toggle=ref(false),segment=ref('Monthly'),checks=ref(['Email']),language=ref('English'),search=ref(''),tab=ref('Overview'),alertOpen=ref(true),slide=ref(0),collapse=ref(false),menu=ref(false),modal=ref<HTMLDialogElement|null>(null),drawer=ref<HTMLDialogElement|null>(null),busy=ref(false),count=ref(3),fileName=ref('No file selected'),email=ref(''),sort=ref(false)
const slides=['Quarterly overview','Team activity','Revenue report'];const rows=computed(()=>{const r=[{name:'Northstar',amount:4200,status:'Success'},{name:'Atlas',amount:1800,status:'Warning'},{name:'Pine',amount:750,status:'Danger'}].filter(r=>r.name.toLowerCase().includes(search.value.toLowerCase()));return sort.value?r.reverse():r})
function toast(s:string){notice.value=s}
function run(){busy.value=true;setTimeout(()=>{busy.value=false;toast('Local task finished')},600)}
</script>
<template><div :class="['studio-kit',`studio-${theme}`]"><h2>Extended variants</h2><p>Local, keyboard-focusable examples. File selection stays in this page; nothing is uploaded.</p><div class="studio-grid sk-extended">
<article><h3>Buttons: variants and outline</h3><div class="studio-row"><button v-for="v in ['primary','success','warning','danger','info','ghost','link']" :key="v" :class="'sk-'+v" @click="toast(v)">{{v}}</button></div><div class="studio-row"><button v-for="v in ['primary','success','warning','danger']" :key="v" :class="['sk-outline-button','sk-'+v]" @click="toast(v+' outline')">{{v}} outline</button></div></article>
<article><h3>Buttons: sizes and disabled</h3><div class="studio-row"><button v-for="s in ['xs','sm','md','lg']" :key="s" :class="'sk-'+s" @click="toast(s)">{{s}}</button></div><div class="studio-row"><button disabled class="sk-primary">Disabled primary</button><button disabled>Disabled default</button><button disabled class="sk-outline-button">Disabled outline</button></div></article>
<article><h3>Buttons: full width and shapes</h3><button class="sk-primary sk-block" @click="toast('Full width action')">Full width action</button><div class="studio-row"><button class="sk-pill" @click="toast('Pill')">Pill</button><button class="sk-square" aria-label="Square add" @click="count++">+</button><button class="sk-round" aria-label="Round add" @click="count++">+</button><button class="sk-sharp" @click="toast('Sharp')">Sharp</button></div></article>
<article><h3>Buttons: active, icons, counters and loading</h3><button :aria-pressed="toggle" :class="{active:toggle}" @click="toggle=!toggle">{{toggle?'Pressed':'Not pressed'}}</button><div class="studio-row"><button @click="count++">+ Add <span class="sk-badge">{{count}}</span></button><button @click="toast('Export sample')">Export ↗</button><button class="sk-primary" :disabled="busy" @click="run">{{busy?'Working…':'Run loading demo'}}</button></div></article>
<article><h3>Button groups: sizes, toolbar and vertical</h3><div class="studio-row" v-for="size in ['sm','md','lg']" :key="size"><div class="sk-group"><button v-for="v in ['Left','Middle','Right']" :key="v" :class="'sk-'+size" @click="toast(v)">{{v}}</button></div></div><div class="studio-row" role="toolbar" aria-label="Sample edit toolbar"><button @click="toast('Bold sample')">B</button><button @click="toast('Italic sample')">I</button><button @click="toast('Link sample')">↗</button></div><div class="sk-vertical"><button v-for="v in ['Overview','Activity','Settings']" :key="v" @click="toast(v)">{{v}}</button></div></article>
<article><h3>Button groups: checks, radio and dropdown</h3><div class="studio-row"><label v-for="v in ['Email','Push']" :key="v" class="sk-choice"><input type="checkbox" :value="v" v-model="checks"/>{{v}}</label></div><div class="sk-group"><button v-for="v in ['Monthly','Yearly']" :key="v" :aria-pressed="segment===v" :class="{active:segment===v}" @click="segment=v">{{v}}</button></div><div class="studio-row sk-popover-wrap"><button class="sk-primary" @click="toast('Split action')">Run sample</button><button aria-label="Open split menu" :aria-expanded="menu" @click="menu=!menu">⌄</button><div v-if="menu" class="sk-popover"><button @click="menu=false;toast('Scheduled locally')">Schedule sample</button><button @click="menu=false">Close menu</button></div></div></article>
<article><h3>Badges: variants, pill, square, dot and positioned</h3><div class="studio-row"><span v-for="v in ['success','warning','danger','info']" :key="v" :class="['sk-badge',v]">{{v}}</span><span class="sk-badge sk-pill">Pill</span><span class="sk-badge sk-sharp">Square</span><span class="sk-status-dot" aria-label="Online"></span>Online</div><div class="studio-row"><button @click="toast('Inbox')">Inbox <span class="sk-badge info">4</span></button><button class="sk-positioned" @click="toast('Notifications')">Notifications<span class="sk-counter">9</span></button></div></article>
<article><h3>Alerts: variants, actions, icon and dismissible</h3><div class="sk-alert info"><strong>ⓘ Report ready</strong><p>Your fictitious report is available.</p><button @click="toast('Report opened')">View sample</button></div><div v-if="alertOpen" class="sk-alert warning"><strong>⚠ Review needed</strong><button aria-label="Dismiss sample alert" @click="alertOpen=false">×</button></div><button v-else @click="alertOpen=true">Restore alert</button><div class="sk-alert success">✓ Complete</div><div class="sk-alert danger">! Local error sample</div></article>
<article><h3>Cards: header, footer, image and horizontal</h3><div class="sk-card"><header><strong>Monthly report</strong></header><div class="sk-card-image" role="img" aria-label="Abstract accent illustration">↗</div><p>Card body with a generated CSS illustration.</p><footer><span>Updated today</span><button @click="toast('Card selected')">Open</button></footer></div><div class="sk-horizontal-card"><div class="sk-card-image" role="img" aria-label="Small abstract illustration">◈</div><div><strong>Team report</strong><small>Horizontal layout</small></div></div></article>
<article><h3>Cards: highlighted, list and grid groups</h3><div class="sk-card sk-highlight"><strong>Highlighted card</strong><p>Use emphasis for a decision, not every surface.</p></div><div class="sk-mini-grid"><div class="sk-card" v-for="n in 2" :key="n">Grid {{n}}</div></div><div class="sk-card" v-for="n in 2" :key="n">List group {{n}}</div></article>
<article><h3>Forms: sizes, textarea and file</h3><label v-for="s in ['sm','md','lg']" :key="s">{{s}} input<input :class="'sk-'+s" :placeholder="s+' example'"/></label><label>Extended memo<textarea rows="2" placeholder="Local memo"></textarea></label><label>Choose local file<input type="file" @change="fileName=($event.target as HTMLInputElement).files?.[0]?.name||'No file selected'"/></label><small>{{fileName}}</small></article>
<article><h3>Forms: validation, input groups and floating labels</h3><label>Validated email<input v-model="email" type="email" :aria-invalid="email.length>0&&!email.includes('@')" :class="{'sk-input-invalid':email.length>0&&!email.includes('@')}"/></label><small>{{email.length>0&&!email.includes('@')?'Include @ in the sample email.':'Helper text.'}}</small><label>Amount<div class="sk-input-group"><span>$</span><input type="number" value="500" aria-label="Grouped amount"/><span>USD</span></div></label><label class="sk-floating"><input placeholder=" " aria-label="Floating name"/><span>Workspace name</span></label></article>
<article><h3>Select, checks, radio, switches and range</h3><label>Single select<select><option>Daily</option><option>Weekly</option></select></label><label>Multiple select<select multiple size="2"><option>Reports</option><option>People</option></select></label><label class="sk-choice"><input type="checkbox"/>Standard check</label><label class="sk-choice"><input type="radio" name="extended-radio"/>Standard radio</label><button role="switch" :aria-checked="toggle" :class="['sk-switch',{on:toggle}]" @click="toggle=!toggle"><i></i><span class="sk-sr">Extended switch</span></button><label>Extended range<input type="range"/></label></article>
<article><h3>Navigation: tabs, vertical and panes</h3><div class="sk-tabs" role="tablist" aria-label="Extended tabs"><button v-for="v in ['Overview','Activity']" :key="v" role="tab" :aria-selected="tab===v" @click="tab=v">{{v}}</button></div><div role="tabpanel" class="sk-tab-panel">{{tab}} content</div><nav class="sk-vertical" aria-label="Extended vertical nav"><button v-for="v in ['Overview','Activity']" :key="v" :aria-current="tab===v?'page':undefined" :class="{active:tab===v}" @click="tab=v">{{v}}</button></nav></article>
<article><h3>Pagination, breadcrumbs, steps and keys</h3><nav aria-label="Extended breadcrumb">Workspace / Catalog / <b>Variants</b></nav><div class="studio-row"><button aria-label="Previous sample page" @click="toast('Previous')">←</button><button v-for="n in 3" :key="n" :aria-current="n===1?'page':undefined" @click="toast('Page '+n)">{{n}}</button><button aria-label="Next sample page" @click="toast('Next')">→</button></div><ol class="sk-stepper"><li class="done">Details</li><li>Review</li><li>Done</li></ol><p>Search <kbd>⌘</kbd> <kbd>K</kbd> · Close <kbd>Esc</kbd></p></article>
<article><h3>Modal, offcanvas, popover and tooltip</h3><div class="studio-row"><button @click="modal?.showModal()">Extended modal</button><button @click="drawer?.showModal()">Extended offcanvas</button><details class="sk-inline-popover"><summary>Popover details</summary><p>Local context. Native disclosure.</p></details><button class="sk-tip-target" aria-label="Extended tooltip" :aria-describedby="`extended-tip-${theme}`">ⓘ<span :id="`extended-tip-${theme}`" class="sk-tooltip" role="tooltip">Focus or hover for details.</span></button></div></article>
<article><h3>Progress, spinners and placeholders</h3><progress value="45" max="100" aria-label="Extended progress 45 percent"></progress><div class="sk-stack"><i style="width:45%"></i><i style="width:25%"></i></div><div class="studio-row"><i class="sk-spinner" aria-label="Extended spinner"></i><span>Loading example</span></div><div class="sk-skeleton"></div><div class="sk-skeleton short"></div><span class="sk-placeholder">Placeholder text</span></article>
<article><h3>List groups: active, disabled and actions</h3><div class="sk-vertical"><button class="active" @click="toast('Active list item')">Active item <span class="sk-badge">3</span></button><button @click="toast('List action')">Action item</button><button disabled>Disabled item</button><button @click="toast('List detail')"><strong>Detailed item</strong><small>Supporting description</small></button></div></article>
<article class="sk-wide"><h3>Tables: basic, striped, hover, border, compact and states</h3><input type="search" v-model="search" aria-label="Extended table search" placeholder="Filter companies"/><div class="sk-table-wrap"><table class="sk-variant-table"><thead><tr><th><button @click="sort=!sort">Company {{sort?'↓':'↑'}}</button></th><th>Status</th><th>Amount</th></tr></thead><tbody><tr v-for="r in rows" :key="r.name"><td>{{r.name}}</td><td><span :class="['sk-badge',r.status.toLowerCase()]">{{r.status}}</span></td><td>${{r.amount.toLocaleString('en-US')}}</td></tr><tr v-if="!rows.length"><td colspan="3">No matching rows <button @click="search=''">Reset filter</button></td></tr></tbody></table></div><small>Striped, hover, bordered, compact and dark-header variants combined here. Status remains textual.</small></article>
<article><h3>Accordion and collapse</h3><details><summary>Extended accordion</summary><p>Native keyboard disclosure.</p></details><button :aria-expanded="collapse" @click="collapse=!collapse">Toggle collapse</button><Transition name="sk-expand"><div v-if="collapse" class="sk-card">Collapsed content is removed from focus order when hidden.</div></Transition></article>
<article><h3>Carousel</h3><div class="sk-carousel" aria-roledescription="carousel" aria-label="Local reports"><Transition name="sk-fade" mode="out-in"><div :key="slide" class="sk-card-image" aria-live="polite">{{slides[slide]}}</div></Transition><div class="studio-row"><button @click="slide=(slide+2)%3" aria-label="Previous slide">←</button><span>{{slide+1}} / 3</span><button @click="slide=(slide+1)%3" aria-label="Next slide">→</button></div></div><small>Manual navigation only. No automatic timer.</small></article>
<article><h3>Avatars, stacks and toast</h3><div class="studio-row"><span v-for="v in ['NS','JD','AM']" :key="v" class="sk-avatar">{{v}}</span><div class="sk-avatars"><span class="sk-avatar">NS</span><span class="sk-avatar">JD</span><span class="sk-avatar">+2</span></div></div><button @click="toast('Extended toast shown')">Extended toast</button></article>
<article><h3>Language select and navbar</h3><nav class="sk-navbar" aria-label="Sample navbar"><strong>{{theme==='folio'?'Folio':'Spark'}}</strong><button :aria-pressed="tab==='Overview'" @click="tab='Overview'">Overview</button><button :aria-pressed="tab==='Activity'" @click="tab='Activity'">Activity</button></nav><label>Sample language<select v-model="language"><option>English</option><option>Español</option><option>Português</option></select></label><small>{{language}} selected. Demo selection, not whole-site translation.</small></article>
<article><h3>Date picker and choice cards</h3><label>Report date<input type="date" value="2026-10-07"/></label><div class="studio-row"><button v-for="v in ['Monthly','Yearly']" :key="v" :aria-pressed="segment===v" :class="['sk-card',{active:segment===v}]" @click="segment=v"><strong>{{v}}</strong><small>{{v==='Monthly'?'Flexible sample plan':'Annual sample plan'}}</small></button></div></article>
<article><h3>Hover card, notifications and error/retry</h3><div class="sk-tip-target" tabindex="0">Northstar profile<span class="sk-tooltip" role="tooltip"><strong>Northstar</strong><small>Sample workspace · 4 members</small></span></div><div class="sk-list-item"><span class="sk-avatar">NS</span><div><strong>Report ready</strong><small>Notification from local demo</small></div><button @click="toast('Marked read')">Mark read</button></div><div class="sk-alert danger">Could not load the fictitious report.<button @click="run">{{busy?'Retrying…':'Retry report'}}</button></div></article>
<article><h3>Message, attachment and close control</h3><div class="sk-card"><strong>Jordan</strong><p>The draft report is ready for review.</p><small>Local message sample, not sent.</small></div><label>Reply sample<textarea placeholder="Draft locally"></textarea></label><button @click="toast('Draft saved locally, not sent')">Save local draft</button><p><span class="sk-badge">⌕ report.pdf · sample attachment</span><button aria-label="Remove sample attachment" @click="toast('Attachment removed locally')">×</button></p></article>
<article><h3>Navigation menu, sidebar, footer and scrollspy</h3><div class="sk-shell"><nav aria-label="Extended sample sidebar"><a :href="`#${theme}-sample-summary`" :aria-current="activeSection==='Summary'?'location':undefined">Summary</a><a :href="`#${theme}-sample-details`" :aria-current="activeSection==='Details'?'location':undefined">Details</a></nav><main ref="spyRoot" class="sk-spy-scroll"><div data-spy="Summary" :id="`${theme}-sample-summary`"><strong>Summary</strong><p>Anchor navigation keeps the section visible.</p></div><div data-spy="Details" :id="`${theme}-sample-details`"><strong>Details</strong><p>Second sample section.</p></div><footer><a :href="`/${theme}/foundations`">Foundations</a> · Local preview</footer></main></div><small>Active section: {{activeSection}}. Native anchors and observed scroll position.</small></article>
</div><Transition name="tpl-feedback"><div v-if="notice" class="sk-toast" role="status">{{notice}}<button aria-label="Dismiss extended toast" @click="notice=''">×</button></div></Transition><dialog ref="modal" class="sk-dialog"><h3>Extended modal</h3><label>Local note<input autofocus/></label><button @click="modal?.close()">Close extended modal</button></dialog><dialog ref="drawer" class="sk-drawer"><h3>Extended offcanvas</h3><p>Native modal focus and Escape.</p><button autofocus @click="drawer?.close()">Close extended offcanvas</button></dialog></div></template>
