<script setup lang="ts">
import {computed,ref} from 'vue'
const props=defineProps<{theme:'folio'|'spark',section?:string}>()
const drawerDialog=ref<HTMLDialogElement|null>(null)
const brand=computed(()=>props.theme==='folio'?'Folio':'Spark')
const checked=ref(true),toggle=ref(true),radio=ref('Monthly'),range=ref(55),tab=ref('Overview'),notice=ref(''),busy=ref(false),query=ref(''),page=ref(1),dialog=ref<HTMLDialogElement|null>(null),menu=ref(false),count=ref(1),selected=ref('Northstar'),invalid=ref(''),rows=ref([{name:'Northstar',status:'Completed',amount:4200},{name:'Atlas',status:'Pending',amount:1800},{name:'Pine',status:'Failed',amount:750},{name:'Field',status:'Completed',amount:3100}])
const filtered=computed(()=>rows.value.filter(r=>r.name.toLowerCase().includes(query.value.toLowerCase())))
const show=(s:string)=>!props.section||props.section===s
function toast(t:string){notice.value=t}
function loading(){busy.value=true;setTimeout(()=>{busy.value=false;notice.value='Local action complete.'},650)}
</script>
<template><div :class="['studio-kit',`studio-${theme}`]">
 <section v-if="show('atoms')" class="studio-section"><h2>Atoms</h2><div class="studio-grid">
 <article><h3>Button</h3><div class="studio-row"><button class="sk-primary" @click="toast('Primary action')">Primary</button><button @click="toast('Secondary action')">Secondary</button><button class="sk-ghost" @click="toast('Ghost action')">Ghost</button><button class="sk-danger" @click="toast('Danger demo only')">Danger</button><button disabled>Disabled</button><button class="sk-primary" @click="loading" :disabled="busy">{{busy?'Loading…':'Async demo'}}</button></div><div class="studio-row"><button class="sk-sm" @click="count++">Small</button><button @click="count++">Default</button><button class="sk-lg" @click="count++">Large</button><span>Pressed {{count-1}} times</span></div></article>
 <article><h3>Icon button / Button group</h3><div class="studio-row"><button aria-label="Add local item" @click="count++">＋</button><button aria-label="Remove local item" @click="count=Math.max(1,count-1)">−</button><button aria-label="Show sample details" @click="toast('Details selected')">···</button><div class="sk-group"><button v-for="t in ['Day','Week','Month']" :key="t" :aria-pressed="tab===t" :class="{active:tab===t}" @click="tab=t">{{t}}</button></div></div></article>
 <article><h3>Badge / Status / Tag</h3><div class="studio-row"><span v-for="s in ['Neutral','Success','Warning','Danger','Info']" :key="s" :class="['sk-badge',s.toLowerCase()]">{{s}}</span><span class="sk-badge sk-outline">Outline</span><button class="sk-badge" @click="toast('Tag removed locally')">Removable ×</button></div></article>
 <article><h3>Avatar / Avatar group</h3><div class="studio-row"><span v-for="(n,i) in ['JD','AM','NS']" :key="n" :class="['sk-avatar',`avatar-${i}`]">{{n}}<i></i></span><div class="sk-avatars"><span class="sk-avatar">NS</span><span class="sk-avatar">JD</span><span class="sk-avatar">+4</span></div><span class="sk-avatar sk-avatar-lg">NS</span></div></article>
 <article><h3>Input / Label / Helper</h3><label>Workspace name<input v-model="selected" placeholder="Name"/></label><small>Default with helper text.</small><label>Disabled<input disabled value="Read-only workspace"/></label><label :class="{'sk-invalid':invalid.length>0}">Required email<input v-model="invalid" type="email" placeholder="name@example.test" :aria-describedby="`sk-error-${theme}`" :aria-invalid="invalid.length>0"/></label><small :id="`sk-error-${theme}`" class="sk-error">{{invalid?'Sample validation error: invalid address.':'Type to preview the invalid state.'}}</small></article>
 <article><h3>Textarea / Select</h3><label>Memo<textarea rows="3" placeholder="Add a local note…"></textarea></label><label>Reporting interval<select v-model="radio"><option>Monthly</option><option>Quarterly</option><option>Yearly</option></select></label></article>
 <article><h3>Checkbox / Radio</h3><label class="sk-choice"><input type="checkbox" v-model="checked"/>Notify about local changes</label><label class="sk-choice"><input type="checkbox" disabled checked/>Disabled selected</label><div class="studio-row"><label class="sk-choice" v-for="v in ['Monthly','Yearly']" :key="v"><input type="radio" :value="v" v-model="radio"/>{{v}}</label></div></article>
 <article><h3>Switch / Slider</h3><button role="switch" :aria-checked="toggle" :class="['sk-switch',{on:toggle}]" @click="toggle=!toggle"><i></i><span class="sk-sr">Enable local notifications</span></button><span>{{toggle?'On':'Off'}}</span><label>Threshold {{range}}%<input type="range" v-model="range" min="0" max="100"/></label></article>
 <article><h3>Progress / Spinner / Skeleton</h3><progress :value="range" max="100" :aria-label="`Progress ${range}%`"></progress><div class="studio-row"><i class="sk-spinner" role="status" aria-label="Sample loading"></i><span>Loading state</span></div><div class="sk-skeleton"></div><div class="sk-skeleton short"></div></article>
 <article><h3>Text / Amount / Separator</h3><strong class="sk-amount">$128,450<span>.80</span></strong><p>Body text for decisions and financial context.</p><small>Secondary content stays readable.</small><hr/><code>tabular-nums · 123456</code><p class="sk-error">Validation and risk use semantic color.</p></article>
 </div></section>
 <section v-if="show('molecules')" class="studio-section"><h2>Molecules</h2><div class="studio-grid">
 <article><h3>Alert</h3><div v-for="s in ['success','warning','danger','info']" :key="s" :class="['sk-alert',s]"><b>{{s}}</b> Sample feedback. No account action.</div></article>
 <article><h3>Card / KPI</h3><div class="sk-card"><div class="sk-card-title">Available balance <button @click="toast('Balance detail')">↗</button></div><strong class="sk-amount">$128,450.80</strong><p class="sk-success">↗ 12.8% vs. last month</p><footer>3 sample accounts <button @click="toast('Account demo')">View →</button></footer></div></article>
 <article><h3>Tabs</h3><div role="tablist" class="sk-tabs"><button v-for="t in ['Overview','Transactions','Payments']" :key="t" role="tab" :aria-selected="tab===t" :class="{active:tab===t}" @click="tab=t">{{t}}</button></div><div role="tabpanel" class="sk-tab-panel">{{tab}} sample content. Keyboard-focusable native buttons.</div></article>
 <article><h3>Accordion / Details</h3><details open><summary>Billing details</summary><p>Example monthly plan. No purchase.</p></details><details><summary>Payment methods</summary><p>No card is connected in this demo.</p></details><details><summary>Workspace permissions</summary><p>Illustrative member roles.</p></details></article>
 <article><h3>Dialog / Drawer</h3><div class="studio-row"><button class="sk-primary" @click="dialog?.showModal()">Open dialog</button><button @click="drawerDialog?.showModal()">Open drawer</button></div><p>Close with Escape or the close control. No outside action.</p><dialog ref="dialog" class="sk-dialog"><h3>Review local change</h3><p>This is a native modal preview.</p><label>Note<input placeholder="Local note"/></label><div class="studio-row"><button @click="dialog?.close()">Cancel</button><button class="sk-primary" @click="dialog?.close();toast('Demo confirmed')">Confirm demo</button></div></dialog></article>
 <article><h3>Menu / Popover / Tooltip</h3><div class="sk-popover-wrap"><button :aria-expanded="menu" @click="menu=!menu">Actions ⌄</button><div v-if="menu" class="sk-popover"><button v-for="a in ['Edit local record','Duplicate sample','Archive demo']" :key="a" @click="menu=false;toast(a)">{{a}}</button></div></div><button class="sk-tip-target" :aria-describedby="`sk-tip-${theme}`">ⓘ<span :id="`sk-tip-${theme}`" role="tooltip" class="sk-tooltip">Hover or focus to show context.</span></button></article>
 <article><h3>Search / Table / Empty state</h3><input v-model="query" aria-label="Search catalog table" type="search" placeholder="Search sample companies…"/><div class="sk-table-wrap"><table><thead><tr><th>Company</th><th>Status</th><th>Amount</th></tr></thead><tbody><tr v-for="r in filtered" :key="r.name"><td>{{r.name}}</td><td><span class="sk-badge" :class="r.status==='Completed'?'success':r.status==='Pending'?'warning':'danger'">{{r.status}}</span></td><td>${{r.amount.toLocaleString('en-US')}}</td></tr><tr v-if="!filtered.length"><td colspan="3"><b>No results</b><p>Try another name or clear search.</p><button @click="query=''">Clear search</button></td></tr></tbody></table></div></article>
 <article><h3>Pagination / Breadcrumb / Stepper</h3><nav aria-label="Catalog breadcrumb">Workspace / Reports / <b>{{brand}}</b></nav><div class="studio-row"><button :disabled="page===1" @click="page--">Previous</button><button v-for="n in 3" :key="n" :aria-current="page===n?'page':undefined" :class="{active:page===n}" @click="page=n">{{n}}</button><button :disabled="page===3" @click="page++">Next</button></div><ol class="sk-stepper"><li v-for="(n,i) in ['Details','Review','Complete']" :key="n" :class="{done:i<page}">{{n}}</li></ol></article>
 <article><h3>Toast / Notification / List item</h3><button class="sk-primary" @click="toast('Changes saved locally')">Show toast</button><div class="sk-list-item"><span class="sk-avatar">NS</span><div><strong>Northstar</strong><small>Monthly report ready</small></div><span class="sk-badge info">New</span></div><div class="sk-list-item"><span class="sk-avatar">JD</span><div><strong>Jordan</strong><small>Approved a sample payment</small></div><small>2h ago</small></div></article>
 </div></section>
 <section v-if="show('charts')" class="studio-section"><h2>Charts</h2><div class="studio-grid"><article><h3>Line / Area / Sparkline</h3><div class="studio-row"><button @click="radio='Monthly'" :class="{active:radio==='Monthly'}">Monthly</button><button @click="radio='Yearly'" :class="{active:radio==='Yearly'}">Yearly</button></div><svg class="sk-chart" viewBox="0 0 300 140" role="img" aria-label="Sample balance trend"><path d="M5 100L35 85L65 90L95 58L125 66L155 49L185 56L215 32L245 40L295 10L295 130L5 130Z" fill="var(--sk-soft)"/><path class="sk-draw" :d="radio==='Yearly'?'M5 110L35 90L65 98L95 80L125 85L155 59L185 75L215 43L245 50L295 25':'M5 100L35 85L65 90L95 58L125 66L155 49L185 56L215 32L245 40L295 10'" fill="none" stroke="var(--sk-accent)" stroke-width="2"/></svg><small>Trend colors identify a series, not approval.</small></article><article><h3>Bar / Stack / Distribution</h3><div class="sk-bars"><button v-for="(v,i) in [34,65,48,88,57,76,96,69]" :key="i" :style="{height:v+'%'}" :aria-label="'Sample bar '+(i+1)+': '+v" @click="toast('Sample bar '+(i+1)+': '+v)"></button></div><div class="sk-stack"><i style="width:74%"></i><i style="width:18%"></i><i style="width:8%"></i></div><small>Payroll 74% · Operations 18% · Growth 8%</small></article><article><h3>Donut / Progress ring</h3><svg class="sk-chart" viewBox="0 0 160 160" role="img" aria-label="78 percent sample completion"><circle cx="80" cy="80" r="53" fill="none" stroke="var(--sk-border)" stroke-width="17"/><circle cx="80" cy="80" r="53" fill="none" stroke="var(--sk-accent)" stroke-width="17" stroke-dasharray="260 333" transform="rotate(-90 80 80)"/><text x="80" y="88" text-anchor="middle">78%</text></svg></article><article><h3>{{theme==='spark'?'Pixel histogram':'Cash-flow comparison'}}</h3><div v-if="theme==='spark'" class="sk-pixels"><div v-for="(v,i) in [7,12,9,16,11,8,13,18,14,11,15,10,16,12,9,14]" :key="i"><i v-for="n in v" :key="n" :class="{dim:n>v*.6}"></i></div></div><div v-else class="sk-comparison"><div><small>Received</small><strong>$86,250</strong><progress value="86" max="100" aria-label="Received 86 percent"></progress></div><div><small>Spent</small><strong>$64,820</strong><progress value="65" max="100" aria-label="Spent 65 percent"></progress></div></div><small>Fictitious values. No connected data.</small></article></div></section>
 <section v-if="show('layouts')" class="studio-section"><h2>Layouts</h2><div class="studio-grid"><article><h3>Sidebar / Header / Navigation</h3><div class="sk-shell"><nav><b>{{brand}}</b><button v-for="n in ['Overview','Reports','Team']" :key="n" :class="{active:tab===n}" @click="tab=n">{{n}}</button></nav><main><header>Workspace <button aria-label="Workspace menu" @click="toast('Local workspace menu')">···</button></header><h3>{{tab}}</h3><div class="sk-skeleton"></div><div class="sk-skeleton short"></div></main></div></article><article><h3>Form / Validation / Action footer</h3><form @submit.prevent="toast('Sample form saved locally')"><label>Project name<input required placeholder="Sample project"/></label><label>Owner<select><option>Northstar</option><option>Jordan</option></select></label><label class="sk-choice"><input type="checkbox" required/>I reviewed the local example</label><footer class="studio-row"><button type="reset">Reset</button><button class="sk-primary">Save sample</button></footer></form></article></div></section>
 <Transition name="tpl-feedback"><div v-if="notice" class="sk-toast" role="status"><span>✓ {{notice}}</span><button @click="notice=''" aria-label="Dismiss notification">×</button></div></Transition><dialog ref="drawerDialog" class="sk-drawer"><h3>Workspace details</h3><p>Native modal drawer with Escape and focus containment.</p><button autofocus @click="drawerDialog?.close()">Close drawer</button></dialog>
</div></template>
